// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = cf.view.inlineTable = cf.view.table.extend({
    toFetch: true,
    dMode: false,
    btns: ['popAdd'],
    itemBtns: ['popEdit', 'del'],
    _dv: [],
    init: function() {
      cf.view.table.prototype.init.call(this);
      if (this.dMode) {
        this.btns = [];
        this.itemBtns = [];
      }
      if (this.callback) {
        return this.listenTo(this.collection, 'all', this.callback);
      }
    },
    _save: function() {
      var c;
      c = this.rCollection;
      c.add(this.model);
      if (c.view._beforeSave) {
        c.view._beforeSave.call(this);
      }
      this.fData.set('_attrs', 'id,version');
      this.fData.save();
      return this.$el.modal("hide");
    },
    formEditOpt: function() {
      return {
        pView: this,
        toFetch: false,
        fData: this.fData,
        _save: this._save
      };
    },
    formAddOpt: function() {
      return {
        pView: this,
        fData: this.fData,
        _save: this._save
      };
    },
    data: function() {
      var ds;
      if (this.form && !this.fData) {
        this.fData = this.form.model;
      }
      ds = this.fData.get(this.entity);
      if (_.isArray(ds)) {
        return ds;
      } else {
        return [];
      }
    }
  });

}).call(this);

//# sourceMappingURL=inlineTable.js.map
