// Generated by CoffeeScript 1.12.7
(function() {
  require('../../res/js/excellentexport/excellentexport.min');

  cf.closeExTb = function() {
    $('.modal').data('_item').closeDlg();
    return app.cache.empty();
  };

  m._.btn.exExcel = function(it, e) {
    var opt;
    opt = util.tBtn('export', null, 'floppy-save', 'btn btn-primary btn-sm');
    opt.attr = {
      onclick: "cf._extb(this,'" + e + "')"
    };
    return opt;
  };

  cf._extb = function(t, et) {
    var cl, tbv;
    tbv = $('#' + et + 'tb').closest('[data-cid]').data('_item');
    cl = tbv.collection;
    return app.dm.tb(app.cache, et, {
      colNum: 100,
      _attrs: function() {
        return '';
      },
      criteriaOpt: function() {
        return _.pick(cl.criteria, 'offset', 'max');
      },
      afterAddAll: function() {
        var bstr, cc;
        this.$('table').attr('id', et + "_ex");
        cc = "return ExcellentExport.excel(this, '" + et + "_ex', '" + et + "_excel_export')";
        bstr = 'btn btn-primary btn-lg btn-block';
        return cf.prompt('数据导出', "<a download=\"" + et + "_" + (new Date().getTime()) + ".xls\" onclick=\"" + cc + "\" class='" + bstr + "'>导出</a>", null, function() {
          var btn;
          btn = this.$('a.btn');
          btn.trigger('click');
          return btn.click(cf.closeExTb);
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=excellentExport.js.map
