// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    entry: function(path, lib, bower) {
      return packDir(path, 'app');
    }
  };

}).call(this);

//# sourceMappingURL=webpack.js.map
