// Generated by CoffeeScript 1.12.7
(function() {
  var r;

  r = function(file) {
    return require("./data/" + file);
  };

  module.exports = {
    community: {
      code: code,
      name: '暖暖',
      resPath: app.env ? '/res' : 'http://ns.activity.liebao.cn',
      url: app.env ? 't.nn.com' : 'nn.activity.liebao.cn'
    },
    data: {
      'meta:code': r('meta')
    },
    member: [code + ",admin"]
  };

}).call(this);

//# sourceMappingURL=data.js.map
