// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    url: 'nn.activity.liebao.cn',
    ftp: '45.33.59.69',
    res_path: "http://ns.activity.liebao.cn/",
    local_path: "http://t.nn.com:3000/res/",
    upload_path: '/opt/node/public/',
    log_path: '/opt/node/public/log/',
    db_host: '127.0.0.1',
    db_port: 27017
  };

}).call(this);

//# sourceMappingURL=setting.js.map
