// Generated by CoffeeScript 1.12.7
(function() {
  require('../../../console/app/meta/common');

  require('./common');

  require('./comment');

  require('./brand');

  require('./product');

  require('./consultant');

  require('./shop');

  require('./school');

  require('./seckilling');

  require('./card');

  require('./order');

  require('./inquiry');

  require('./answer');

  cf.bdst = {
    entities: ['post', 'content', 'shop', 'product', 'school', 'consultant', 'card', 'seckilling']
  };

  cf._stat = {
    inquiry: {
      className: 'col-md-6',
      colNum: 4
    },
    order: {
      className: 'col-md-6',
      itemBtns: ['popView', 'processOrderStatus', 'del'],
      colNum: 4
    },
    answer: {
      className: 'col-md-6',
      itemBtns: ['popView', 'processAnswerStatus', 'del'],
      colNum: 3
    },
    guestBook: {
      className: 'col-md-6',
      colNum: 3
    }
  };

}).call(this);

//# sourceMappingURL=admin.js.map
