// Generated by CoffeeScript 1.12.7
(function() {
  m.inquiry = {
    prop: [
      _ep('username'), {
        code: 'shop',
        showText: function(v) {
          if (v) {
            return tu.link((v._e = 'shop' && v));
          }
        }
      }, {
        code: 'consultant',
        showText: function(v) {
          if (v) {
            return tu.link((v._e = 'consultant' && v), 'username');
          }
        }
      }, _ep('phone'), {
        code: 'content',
        type: 'textarea'
      }, m._pic('head')
    ],
    filter: {
      username: 'text:s:mt',
      phone: 'text:s:mt'
    },
    viewOpt: {
      btns: ['close'],
      cols: '100px,auto'
    }
  };

}).call(this);

//# sourceMappingURL=inquiry.js.map
