// Generated by CoffeeScript 1.12.7
(function() {
  m.order = {
    prop: [
      _ep('status'), _ep('username'), {
        code: 'shop',
        showText: function(v) {
          if (v) {
            v._e = 'shop';
            return tu.link(v);
          }
        }
      }, {
        code: 'consultant',
        showText: function(v) {
          if (v) {
            v._e = 'consultant';
            return tu.link(v, 'username');
          }
        }
      }, _ep('user:gender'), _ep('age'), _ep('phone'), _ep('symptom'), {
        code: 'appointmentTime',
        type: 'date'
      }, _ep('memo'), _ep('proc')
    ],
    filter: {
      username: 'text:s:mt',
      phone: 'text:s:mt'
    },
    viewOpt: {
      btns: ['close']
    }
  };

  require('./status/order');

}).call(this);

//# sourceMappingURL=order.js.map
