// Generated by CoffeeScript 1.12.7
(function() {
  m.school = {
    prop: [
      _ep('title'), _ep('row'), _ep('area'), {
        code: 'address',
        ph: '请输入完整地址',
        events: {
          click: function(e) {
            var t, v;
            t = util.ct(e);
            v = t.val();
            if (!v) {
              return t.val(this.$('.areaWt').attr('area'));
            }
          }
        }
      }, _ep('phone'), _ep('description'), m.content.prop.codeBy('status'), m._pic('slide')
    ],
    listOpt: {
      btns: ['exExcel', 'topAdd']
    }
  };

}).call(this);

//# sourceMappingURL=school.js.map
