// Generated by CoffeeScript 1.12.7
(function() {
  require('../../../../lib/widget/editor/areaCode');

  m.shop = {
    prop: [
      {
        code: 'org',
        type: 'select',
        attrs: {
          entity: 'org',
          keyVal: '_id,title'
        },
        showText: function(v) {
          if (v) {
            return v.title || '';
          } else {
            return '';
          }
        },
        events: {
          'change select': function(e) {
            var t, v;
            t = util.ct(e);
            v = t.val();
            if (v === '0') {
              this.model.set('org', 0);
            } else {
              this.model.set('org', {
                _id: v,
                title: t.children(':selected').text()
              });
            }
            e.stopPropagation();
            return e.preventDefault();
          }
        },
        isShow: function() {
          return user.hasRole('admin,manager');
        }
      }, m._link('title'), _ep('row'), _ep('area'), {
        code: 'address',
        ph: '请输入完整地址',
        events: {
          click: function(e) {
            var t, v;
            t = util.ct(e);
            v = t.val();
            if (!v) {
              return t.val(this.$('.areaWt').attr('area'));
            }
          }
        }
      }, _ep('phone'), {
        code: 'operTime',
        xtype: 'dTime',
        attrs: {
          minView: 2,
          startView: 4
        }
      }, m._number('space'), _ep('goodAtBrand', {
        code: 'brand'
      }), m._radio('park', {
        attrs: {
          data: ['是', '否']
        }
      }), m._radio('dropIn', {
        attrs: {
          data: ['是', '否']
        }
      }), _ep('level'), _ep('description'), m._itemTable('comment'), m.content.prop.codeBy('status'), m._pic('slide'), m._user({
        code: 'owner'
      })
    ],
    selectOpt: '_id,title,postcode,phone,address',
    btn: {
      showInTd: function(it) {
        return util.iBtn("user", 'showInTd');
      }
    },
    listOpt: {
      btns: ['exExcel', 'topAdd'],
      criteriaOpt: function() {
        if (!user.isAdmin() && user.orgs && user.orgs.length) {
          return {
            q: {
              'org._id': user.orgs[0]._id
            }
          };
        } else {
          return {};
        }
      },
      afterShow: function(e, p) {
        var m;
        m = this.findData(e);
        return app.dm.tb(p, 'consultant', {
          criteriaOpt: function() {
            return {
              q: {
                'shop._id': m.id
              }
            };
          }
        });
      }
    },
    filter: {
      title: 'text:s:mt'
    }
  };

  if (cf.mob) {
    $.extend(true, meta.shop.consultant, {
      noCol: true,
      noLabel: true
    });
  }

}).call(this);

//# sourceMappingURL=shop.js.map
