// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = _.extend(require('../../_mod/group/i18n/zh'), {
    siteName: '猎豹外文社',
    department: '部门',
    task: '分享'
  });

}).call(this);

//# sourceMappingURL=server_zh.js.map
