// Generated by CoffeeScript 1.12.7
(function() {
  var fixList;

  fixList = {
    focusCursor: function() {
      var inputObj, item, len;
      inputObj = document.getElementsByTagName('input');
      len = inputObj.length;
      while (i < len) {
        item = inputObj[i];
        if (item.type === 'text') {
          item.focus();
          item.blur();
          break;
        }
        i++;
      }
    },
    flush: function() {
      var body;
      body = document.getElementsByTagName('body')[0];
      body.focus();
      body.blur();
    }
  };

  window.onload = function() {
    var k, v;
    for (k in fixList) {
      v = fixList[k];
      v();
    }
  };

}).call(this);

//# sourceMappingURL=android.js.map
