// Generated by CoffeeScript 1.12.7
(function() {
  var r;

  r = function(file) {
    return require("./data/" + file);
  };

  module.exports = {
    community: {
      code: code,
      name: '心路明',
      resPath: _env ? '/res' : 'http://s.postenglishtime.com',
      url: _env ? 't.xlm.com' : 'yukof.postenglishtime.com',
      nav: [
        {
          label: "首页",
          href: "/",
          cur: 'index',
          labelCls: "label-info"
        }
      ]
    },
    data: {
      'course:title': r('course'),
      'project:title': r('project'),
      'startup:title': r('title'),
      'team:title': r('title'),
      'market:title': r('title'),
      'house:title': r('title'),
      'furniture:title': r('title'),
      'device:title': r('title'),
      'staff:title': r('title'),
      'campaign:title': r('title')
    }
  };

}).call(this);

//# sourceMappingURL=data.js.map
