// Generated by CoffeeScript 1.12.7
(function() {
  var c;

  require('./en');

  c = require('../../console/i18n/en');

  $.extend(window._i, c, {
    demo: 'demo'
  });

}).call(this);

//# sourceMappingURL=console_en.js.map
