// Generated by CoffeeScript 1.12.7
(function() {
  require('./style/wt.sass');

  cf.loadLibTmpl = function(name) {
    return require("../../../lib/tmpl/" + name + ".jade");
  };

  require('../../../res/js/jquery-timeago/jquery.timeago');

  jQuery.timeago.settings.allowFuture = true;

  jQuery.timeago.settings.localeTitle = true;

  cf._uOpt = {
    check: function() {
      return true;
    }
  };

  require("../../../lib/wtRouter")();

}).call(this);

//# sourceMappingURL=wt.js.map
