// Generated by CoffeeScript 1.12.7
(function() {
  var area, dTime, listEditor, lost;

  dTime = require('../../../lib/widget/editor/dTime');

  area = require('../../../lib/widget/editor/areaCode');

  listEditor = require('../../../lib/widget/editor/listEditor');

  require('../../../lib/meta/extend/captcha')('vcode', "http://zhaohui.liebao.cn/captcha/v1/v3.2?_token=" + _token);

  _.extend(String.prototype, {
    trim: function() {
      return this.replace(/^\s+|\s+$/g, "");
    },
    startsWith: function(pattern) {
      return this.lastIndexOf(pattern, 0) === 0;
    }
  });

  window.isIE = function(ver) {
    var b;
    b = document.createElement('b');
    b.innerHTML = '<!--[if IE ' + ver + ']><i></i><![endif]-->';
    return b.getElementsByTagName('i').length === 1;
  };

  window._setHeight = function(h) {
    var ifr;
    ifr = $('#_setHeight');
    return ifr.attr('src', ifr.attr('src').split('=')[0] + '=' + h);
  };

  cf.addMemoLink = function() {
    var a, li;
    li = $('#lostIn');
    a = $('<a style="color:red">点击查看示例</a>').click(function() {
      if (li.val().trim().length === 0) {
        return li.val('示例：皇家守卫、银澜天翔、黄金宝箱+10*4、暗影修罗、生命宝石*689、星曜之石*2、高级坐骑丹*4、黄金宝箱+11*3、强化套装石(护手)*592、强化套装石(护腿)*195、强化套装石(鞋子)*322、强化套装石(头盔)*227、强化套装石(衣服)*13玄冥之盔、圣心之盾、玄冥护手、玄冥之靴、毒戒指、神·大天使之杖、毒戒指、冰项链、玄冥护腿、玄冥之铠。');
      }
    });
    li.click(function() {
      if ($(this).val().indexOf('示例') === 0) {
        return li.val('');
      }
    });
    return li.parent().prev().append('<br/>').append(a);
  };

  $.extend(meta.common, {
    tel: {
      type: "tel",
      valid: {
        telephone: true
      }
    },
    code: {
      type: 'custom',
      label: "短信验证码",
      id: 'verification',
      valid: {
        required: true
      },
      content: function() {
        return $("<div><input name='code' class='form-control'><button type='button' class='verify btn btn-default'>免费获取验证码</button></div>");
      }
    }
  });

  lost = ['ltime', 'ftime', 'lose', 'desc'];

  _i['valid.required'] = '必须填写';

  $.extend(meta, {
    question: {
      name: {
        valid: {
          required: true
        }
      },
      account: {
        label: '游戏账号',
        valid: {
          required: true
        }
      },
      type: {
        type: 'select',
        label: '请选择问题',
        val: 2,
        data: {
          2: '装备物品被盗',
          1: '账号被盗',
          3: '二级密码找回'
        },
        trigger: 'change',
        events: {
          change: function(e) {
            var v;
            v = util.ct(e).val();
            if (v === '1' || v === '3') {
              cf._itemBk = this.metaOpt.item.splice(3, 1);
              return cf._noId = true;
            } else {
              cf._noId = false;
              if (cf._itemBk) {
                return this.metaOpt.item.splice(3, 0, cf._itemBk[0]);
              }
            }
          }
        }
      },
      order: {
        valid: {
          required: true
        }
      },
      gid: {
        type: 'select',
        url: "http://zhaohui.liebao.cn/f/gamelist?_token=" + _token,
        st: 'jsonp',
        jsonp: true
      },
      bind: {},
      regtime: meta.exCom('startedDate', {
        attrs: {
          noVal: true
        },
        valid: {
          required: true
        }
      }),
      people: {
        type: 'radio',
        inline: true,
        data: {
          1: '1人',
          2: '2人',
          3: '3人',
          '多人': '多人'
        },
        valid: {
          required: true
        }
      },
      region: {
        valid: {
          required: true
        }
      },
      regaddr: {
        type: 'holder',
        xtype: area,
        attrs: {
          prop: 'regaddr_code',
          text: 'regaddr',
          auto: true,
          noSv: true
        }
      },
      local1: {
        type: 'holder',
        xtype: area,
        id: 'localss1',
        attrs: {
          prop: 'local1',
          text: 'localText1',
          auto: true,
          noSv: true
        }
      },
      local2: {
        type: 'holder',
        xtype: area,
        attrs: {
          prop: 'local2',
          text: 'localText2',
          auto: true,
          noSv: true
        }
      },
      gameRole: {
        type: 'text',
        valid: {
          required: true
        }
      },
      regcard: {
        type: 'text',
        valid: {
          required: true,
          pattern: /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/
        }
      },
      playcard: {
        type: 'text',
        valid: {
          required: true,
          pattern: /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/
        }
      },
      accStr1: {
        type: 'label',
        val: '<a class="showId">点击这里上传</a><small style="margin-left:20px">如果已绑定身份证，申请找回是必须上传身份证照片，<span style="color:red;font-weight: bold">否则不予处理</span>。</small>',
        isShow: function() {
          return !cf._noId;
        },
        events: {
          'click .showId': function(e) {
            var _imgcb, p, that, tp;
            cf._fsp = p = util.ct(e).parent().parent();
            tp = $('.showIdBox');
            if (tp.is(':visible')) {
              cf._srHeight -= 409;
            } else {
              cf._srHeight += 409;
            }
            _setHeight(cf._srHeight);
            if (tp.length) {
              tp.toggle();
              return;
            } else {
              p.html(cf.rtp('showId'));
            }
            p.on('click', '.delPic', function(e) {
              var name;
              name = util.ct(e).attr('picName');
              if (cf._fsName) {
                return $.getJSON("http://zhaohui.liebao.cn/upd/v3.2?_token=" + _token + "&type=card&name=" + cf._fsName, function(res) {
                  if (res.ret === 1) {
                    p.find('.imgBox').empty();
                    cf._fsName = null;
                    cf._fs = null;
                  } else {
                    popMsg(res.msg, 'warning');
                  }
                  return p.find('[type="file"]').val('');
                });
              } else {
                p.find('.imgBox').empty();
                p.find('.upload').addClass('disabled');
                return p.find('[type="file"]').val('');
              }
            });
            if (isIE('8')) {
              _imgcb = function() {
                var _if, doc, innerHTML, path, res;
                _setHeight(367 + 180 * 2 + 360);
                _if = $('#_iframe');
                doc = _if[0].contentDocument;
                innerHTML = doc.body.innerHTML;
                if (innerHTML.slice(0, 5).toLowerCase() === '<pre>' && innerHTML.slice(-6).toLowerCase() === '</pre>') {
                  innerHTML = doc.body.firstChild.firstChild.nodeValue;
                }
                res = eval("(" + innerHTML + ")");
                if (+res.ret === 1) {
                  cf._fsName = res.name;
                  path = 'http://zhaohui.liebao.cn/pic/' + res.name;
                  $('.imgBox').append("<img src='" + path + "'/>" + (tu.icon('remove btn btn-default delPic')));
                  popMsg('上传文件成功');
                } else {
                  popMsg(res.msg, 'warning');
                }
              };
              $('.uploadImg').change(function() {
                var _if, cb;
                _if = $('#_iframe');
                cb = function() {
                  _imgcb();
                  return _if.unbind('load', cb);
                };
                _if.bind('load', cb);
                $('#_form').submit();
              });
              return;
            }
            if (cf._showFs == null) {
              cf._showFs = function() {
                var rd;
                p = cf._fsp;
                if (!cf._fs) {
                  return;
                }
                rd = new FileReader();
                _setHeight(367 + 180 * 2 + 360);
                rd.onload = function(e) {
                  return p.find('.imgBox').html("<img src='" + e.target.result + "'/>" + (tu.icon('remove btn btn-default delPic')));
                };
                return rd.readAsDataURL(cf._fs);
              };
            }
            cf._showFs();
            p.find('[type="file"]').change(function(e) {
              cf._fs = util.ct(e)[0].files[0];
              if (cf._fs.size > 3 * 1024 * 1000) {
                return popMsg('文件太大', 'warning');
              } else {
                cf._showFs();
                return p.find('.upload').removeClass('disabled');
              }
            });
            that = this;
            return p.find('.upload').click(function(e) {
              var fd, t;
              t = util.ct(e);
              t.addClass('disabled');
              fd = new FormData();
              fd.append('img', cf._fs);
              fd.append('type', 'card');
              that = that;
              return $.ajax({
                type: 'POST',
                url: "http://zhaohui.liebao.cn/upd/v3.2?_token=" + _token,
                data: fd,
                contentType: false,
                processData: false,
                success: function(res) {
                  res = JSON.parse(res);
                  if (+res.ret === 1) {
                    popMsg('上传文件成功');
                  } else {
                    popMsg(res.msg, 'warning');
                  }
                  return cf._fsName = res.name;
                }
              });
            });
          }
        }
      },
      accStr2: {
        type: 'label',
        val: '<a class="btn btn-default yes" style="color: red;margin-right: 30px">是</a><a class="btn btn-default no" style="color: red">否</a>',
        events: {
          'click .closeBox': function(e) {
            util.ct(e).closest('.panel').remove();
            cf._srHeight -= 312;
            return _setHeight(cf._srHeight);
          },
          'click .yes': function(e) {
            var p;
            p = util.ct(e).parent().parent();
            p.find('.panel').remove();
            return p.append(cf.rtp('yesBox'));
          },
          'click .no': function(e) {
            var p;
            p = util.ct(e).parent().parent();
            p.find('.panel').remove();
            return p.append(cf.rtp('noBox'));
          },
          'click .showRecord': function(e) {
            var p, tb;
            p = util.ct(e).parent().parent();
            tb = $('.showRecordBox');
            if (tb.is(':visible')) {
              cf._srHeight -= 312;
            } else {
              cf._srHeight += 312;
            }
            _setHeight(cf._srHeight);
            if (tb.length) {
              tb.toggle();
            } else {
              p.append(cf.rtp('showRecord'));
              return new listEditor({
                form: this,
                name: 'payList',
                itemTmpl: 'payRecord',
                parent: p.find('.refresh'),
                newData: function() {
                  return {};
                },
                addLimit: function(e) {
                  if (this.data.length === 30) {
                    popMsg('只能添加30项', 'warning');
                    return true;
                  }
                  return false;
                },
                data: this.model.get('payList') || [{}, {}, {}, {}, {}],
                afterDel: function() {
                  cf._srHeight -= 45;
                  return _setHeight(cf._srHeight);
                },
                afterAddOne: function(ctn, d) {
                  dTime.fun({
                    parent: ctn.find('.date')
                  });
                  if (d.payType) {
                    ctn.find('select').val(d.payType);
                  }
                  cf._srHeight += 45;
                  return _setHeight(cf._srHeight);
                }
              });
            }
          }
        }
      },
      ltime: meta.exCom('startedDate', {
        valid: {
          required: true
        },
        attrs: {
          noVal: true
        }
      }),
      ftime: meta.exCom('startedDate', {
        valid: {
          required: true
        },
        attrs: {
          noVal: true
        }
      }),
      lose: {
        id: 'lostIn',
        type: 'textarea',
        valid: {
          required: true
        }
      },
      desc: {
        type: 'textarea',
        valid: {
          required: true
        }
      },
      _: {
        item: [
          {
            items: ['type', 'account', 'vcode'],
            btns: ['next'],
            callback: function() {
              this.$('.refresh .col-md-8').attr('class', 'col-md-4 rels');
              this.$('.next').css({
                float: 'left'
              });
              return _setHeight(384);
            },
            nextTab: function(callback) {
              var that;
              that = this;
              if (that.__tab1Pass) {
                callback.call(this);
                return;
              }
              return $.getJSON("http://zhaohui.liebao.cn/f/checkpp?_token=" + _token + "&vcode=" + (this.model.get('vcode')) + "&pp=" + (this.model.get('account')) + "&callback=?", function(item) {
                if (item.ret !== true) {
                  popMsg(item.msg || '账号错误或者不存在', 'warning');
                  return $('.changeCaptcha').trigger('click');
                } else {
                  that.meta.type.disabled = true;
                  that.meta.account.disabled = true;
                  that.removeItems('vcode');
                  that.__tab1Pass = true;
                  return callback.call(that);
                }
              });
            }
          }, {
            items: ['name', 'tel', '_clearfix', 'gid', 'gameRole', '_clearfix', 'region', 'bind', '_clearfix', 'regtime', '_clearfix', 'regaddr', 'people', 'local1', 'local2'],
            btns: ['prev', 'next'],
            callback: function() {
              var next;
              this.$('.form-group:eq(7)').prevAll('.form-group').addClass('col-md-6');
              next = this.$('.form-group:eq(6)').nextAll('.form-group');
              next.children('label').attr('class', 'control-label col-md-2');
              next.find('.col-md-8').attr('class', 'col-md-10');
              this.$('.foot label').attr('class', 'control-label col-md-2');
              this.$('.foot .btnCtn').attr('class', 'col-md-9 btnCtn');
              return _setHeight(710);
            },
            nextTab: function(cb) {
              var v;
              v = this.model.get('regaddr');
              if (!v || !v.length) {
                return this.msg('账号注册地点必须选择');
              } else {
                v = this.model.get('local1');
                if (!v || !v.length) {
                  return this.msg('常用登陆地点1必须选择');
                } else {
                  return cb.call(this);
                }
              }
            }
          }, {
            items: ['regcard', 'playcard', 'accStr1', 'accStr2'],
            callback: function() {
              this.$('.col-md-8:eq(0)').attr('class', 'col-md-4 rels');
              this.$('.col-md-8:eq(0)').attr('class', 'col-md-4 rels');
              if (isIE(8)) {
                this.$('.col-md-8:eq(0)').attr('class', 'col-md-10');
                this.$('.col-md-8:eq(0)').attr('class', 'col-md-10');
              }
              if (cf._fs) {
                this.$('.showId').trigger('click');
              }
              if (this.model.get('payList')) {
                this.$('.showRecord').trigger('click');
              }
              cf._srHeight = 420;
              _setHeight(cf._srHeight);
              return $('.showId').trigger('click');
            },
            nextTab: function(cb) {
              var i, it, j, k, len, len1, len2, ref, ref1, ref2;
              ref = $("input[name='payNum']");
              for (i = 0, len = ref.length; i < len; i++) {
                it = ref[i];
                if (!/^\d{6,18}$/.test($(it).val())) {
                  popMsg('订单号格式错误，应该是7到18位数字', 'warning');
                  return;
                }
              }
              ref1 = $("select[name='payType']");
              for (j = 0, len1 = ref1.length; j < len1; j++) {
                it = ref1[j];
                if (!$(it).val() || $(it).val() === '0') {
                  popMsg('请选择支付方式', 'warning');
                  return;
                }
              }
              ref2 = $("input[name='payPrice']");
              for (k = 0, len2 = ref2.length; k < len2; k++) {
                it = ref2[k];
                if (!$(it).val() || +$(it).val() === 0) {
                  popMsg('请输入正确的充值金额', 'warning');
                  return;
                }
              }
              if (cf._noId === false && !cf._fsName) {
                popMsg('请上传身份证照片', 'warning');
                return;
              }
              return cb.call(this);
            },
            btns: ['prev', 'next']
          }, {
            items: lost,
            btns: ['prev', 'next'],
            callback: function() {
              this.$('.col-md-8:eq(0)').attr('class', 'col-md-4');
              this.$('.col-md-8:eq(0)').attr('class', 'col-md-4');
              cf.addMemoLink();
              return _setHeight(605);
            }
          }
        ],
        "export": {
          search: function() {
            return ['tel', 'order', 'vcode'];
          },
          lost: function() {
            lost.unshift('accStr1');
            return lost;
          }
        }
      }
    }
  });

}).call(this);

//# sourceMappingURL=meta.js.map
