// Generated by CoffeeScript 1.12.7
(function() {
  require('../model/entity');

  require('../model/entities');

  require('../view/_tag');

  require('../view/tag');

  require('../view/_modal');

  require('../view/model');

  require('../view/form/form');

  require('../view/view');

  require('../view/collection/app');

  require('../view/collection/pagination');

}).call(this);

//# sourceMappingURL=h5.js.map
