// Generated by CoffeeScript 1.12.7
(function() {
  require('../widget/menu/side/app');

  require('../widget/menu/top/app');

  require('../func/entityAction');

}).call(this);

//# sourceMappingURL=h5_ft_login.js.map
