// Generated by CoffeeScript 1.12.7
(function() {
  require('./h5');

  require('../../module/console/app/lib/consoleTableBtns');

  require('../view/collection/filter');

  require('../view/collection/table');

  require('../view/collection/jsonTable');

  require('../view/portal');

  require('../widget/editor/selectBox/multiSelect');

  require('../widget/refFileCollection');

  require('../widget/editor/ref/app');

  require('../widget/editor/rich/sn/app');

  require('../widget/editor/rich/md/app');

  require('../widget/editor/dTime');

  require('../widget/editor/strList/app');

  require('../widget/editor/propEditor/app');

  require('../widget/editor/inlineObj');

  require('../func/showInTd');

  require('../func/inlineBtn');

  require('../func/popBtn');

  require('../func/ipBtn');

  require('../widget/menu/top/consoleMenu');

}).call(this);

//# sourceMappingURL=h5_mgm.js.map
