// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = function(ctx, req, rsp) {
    var code, qu;
    qu = req.query;
    code = ctx.c.code;
    return {
      moodTag: function(cb) {
        return dao.find(code, 'moodTag', {}, {}, function(res) {
          return cb(null, res);
        });
      },
      pd: function(cb) {
        return dao.get(code, 'thread', {
          _id: qu.tid
        }, function(thread) {
          if (!thread) {
            cb(null, -1);
            return;
          }
          return dao.get(code, 'group', {
            _id: thread.group._id
          }, function(group) {
            if (!group) {
              cb(null, -1);
              return;
            }
            return dao.get(code, 'groupMember', {
              _id: qu.gmid
            }, function(uInfo) {
              var cd;
              if (!uInfo) {
                cb(null, -1);
                return;
              }
              cd = thread.dateCreated;
              _.extend(ctx, thread, {
                intro: _.compact([uInfo.industry, uInfo.jobTitle, uInfo.company]),
                statement: uInfo.statement,
                hasEdit: false,
                task: group.task.findBy('subData.code', thread.form.code),
                hasBack: false,
                group: group,
                hasAdv: true,
                hasQrcode: true,
                hasComment: true,
                title: thread.title ? util.adjustText(thread.title, 20) : thread.user.username + "的分享",
                subTitle: cd.pattern('MM月dd日') + (" 第" + ((-new Date(group.startedDate).minusTime(cd)) + 1) + "天")
              });
              return cb();
            });
          });
        });
      }
    };
  };

}).call(this);

//# sourceMappingURL=mobReadThread.js.map
