// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    url: 'ear.eclubnet.com',
    ftp: '45.33.59.69',
    res_path: "http://s.wikibeijing.com/",
    local_path: "http://t.ear.com:3000/res/",
    upload_path: '/opt/node/public/',
    log_path: '/opt/node/public/log/',
    db_host: '127.0.0.1',
    db_port: 27017
  };

}).call(this);

//# sourceMappingURL=setting.js.map
