// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    outPut: '/Users/alex/Projects/k-zk-webmanager/src/main/webapp/static/js/'
  };

}).call(this);

//# sourceMappingURL=setting.js.map
