// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = cf.view.slide = cf.view.tag.extend({
    parent: null,
    index: 0,
    className: 'carousel slide',
    auto: true,
    slideOpt: {
      interval: 5000
    },
    events: {
      'drag .carousel-inner': 'slideIt',
      'flick .carousel-inner': 'slideIt'
    },
    slideIt: function(e) {
      if ('horizontal' === e.orientation) {
        if (this.sliding) {
          return true;
        }
        if (1 === e.direction) {
          this.$el.carousel('prev');
        } else {
          this.$el.carousel('next');
        }
        e.preventDefault();
        e.stopPropagation();
      }
      return true;
    },
    preRender: function() {
      var id, len;
      id = util.randomChar(4);
      if (this.indicator) {
        len = this.$('.item').length;
        if (len < 2) {
          len = false;
        }
      }
      this.$el.attr('id', id);
      this.$el.append(cf.rtp(require('./slideBtn.jade'), {
        controller: this.controller,
        indicator: len,
        _sid: id
      }));
      this.$('.carousel-indicators').children(":eq(" + this.index + ")").addClass('active');
      this.$('.carousel-inner').children(":eq(" + this.index + ")").addClass('active');
      this.$el.carousel(this.slideOpt);
      this.$el.on('slide.bs.carousel', (function(_this) {
        return function() {
          return _this.sliding = true;
        };
      })(this));
      return this.$el.on('slid.bs.carousel', (function(_this) {
        return function() {
          return _this.sliding = false;
        };
      })(this));
    }
  });

}).call(this);

//# sourceMappingURL=app.js.map
