// Generated by CoffeeScript 1.12.7
(function() {
  var form, list, userOpt;

  form = require("../../lib/view/form");

  list = require("../../lib/view/list");

  userOpt = meta.user;

  module.exports = {
    routes: {
      '!/club': 'club',
      '!/club/one(/:p)': 'one'
    },
    clubItems: function() {
      if (user.hasRole('organizer,club')) {
        return _userBizInfo();
      } else {
        if (user.get('introduction')) {
          return ['username', 'gender', 'email', 'industry', 'title', 'introduction'];
        } else if (true) {
          return ['username', 'gender', 'introduction', 'more_info'];
        }
      }
    },
    club: function() {
      var items, max, w;
      items = this.clubItems();
      w = screen.width / (cf.mob ? 4 : 15);
      max = 20;
      return new list({
        toFetch: true,
        entity: 'user',
        mode: 'blank',
        _pagination: true,
        context: {
          title: ' ',
          foot: true
        },
        criteriaOpt: {
          refFile: 'isNotNull',
          max: max,
          _attrs: 'username,refFile'
        },
        parent: this.ctn,
        events: function() {
          return $.extend(list.prototype.events, {
            'click .viewInfo': function(e) {
              return this._vFrom = new form({
                mode: 'modal',
                items: items,
                btns: ['closeDlg'],
                viewMode: true,
                context: function() {
                  return {
                    foot: true,
                    bodyStyle: 'panel-body',
                    head: false
                  };
                },
                entity: 'user',
                model: this.findData(e)
              });
            }
          });
        },
        afterAddAll: function() {
          if (user.hasRole('organizer,club')) {
            $.extend(meta.user._, {
              filter: {
                username: 'text:s',
                title: 'text:s',
                industry: 'select:l'
              }
            });
            this.$('.head').addClass('clearfix').append('<div class="toolbar"></div>');
            return this.setTools(true);
          }
        },
        addOne: function(item) {
          var d, res;
          d = item.attributes;
          res = util.resPath("portrait-" + d.id + ".jpg");
          return this.ctn.append("<img class='viewInfo' id='p-" + d.id + "' style='width:" + w + "px;height:" + w + "px' src='" + res + "'/>");
        },
        callback: function() {
          var cls, href, text;
          cls = _st.btn('primary', 'lg', true);
          if (user.hasRole('club,organizer')) {
            text = "<a class='" + cls + " more'>更多...</a>";
          } else {
            this.$('.head').before(cf.tmpl.alert({
              type: 'success',
              title: 'Club简介',
              icon: 'gift',
              msg: '<p>与靠谱的小伙伴们在一起：分享、体验、成长。</p>'
            }));
            href = util.navUrl('profile');
            text = "<a class='" + cls + " disabled' href='" + href + "'>申请加入P.E.T. Club</a>";
            this.$('.foot').append(cf.tmpl.alert({
              type: 'danger',
              title: '申请条件',
              icon: 'info-sign',
              msg: '<p>拥有积极价值观，做过一次以上主持人</p>'
            }));
          }
          return this.$('.foot').append(text);
        }
      });
    },
    one: function(id) {
      return new form({
        items: this.clubItems(),
        btns: [],
        parent: this.ctn,
        viewMode: true,
        context: function() {
          return {
            foot: true,
            bodyStyle: 'panel-body',
            head: false
          };
        },
        entity: 'user',
        data: {
          id: id
        }
      });
    },
    profile: function(mode) {
      var data, m;
      data = user.attributes;
      m = meta.user._;
      m.editFormOpt = {
        cleanAll: true,
        parent: this.ctn,
        title: '用户信息',
        toFetch: false,
        btns: ['save'],
        data: data,
        _saveSuccess: function() {
          $('#content').html(cf.tp.vDone({
            title: '信息跟新完成',
            content: '谢谢您的支持，我们承诺会把活动做的更好。',
            link: {
              title: '后英语时代主页',
              url: 'http://postenglishtime.com'
            }
          }));
          return util.sTop();
        }
      };
      m.editFormOpt.spItem = data.phone ? 'fullInfo' : 'simple';
      return app._data.fun('edit', 'user', user.id);
    }
  };

}).call(this);

//# sourceMappingURL=profile_pet.js.map
