// Generated by CoffeeScript 1.12.7
(function() {
  require('./style/main.css');

  cf.rsPre = cf.actPre = 'http://online28.wan.liebao.cn/onlineRest/';

  $.extend(cf, {
    loadTmpl: function(name) {
      try {
        return require("./tmpl/" + name + ".jade");
      } catch (error) {
        return require("../../console/tmpl/" + name + ".jade");
      }
    },
    loadLibTmpl: function(name) {
      return require("../../../lib/tmpl/" + name + ".jade");
    },
    _init: function() {
      Backbone.Model.setPost();
      cf.id = 'id';
      Backbone.Model.prototype.idAttribute = cf.id;
      cf.community = {
        name: '在线棋牌',
        resPath: '/'
      };
      return require("./meta/meta");
    },
    _rOpt: {
      dfPath: 'data'
    },
    _uOpt: {
      menu: [
        {
          icon: 'hdd',
          key: 'data'
        }
      ],
      entities: [
        {
          key: 'channel',
          row: 10
        }, {
          key: 'pay',
          row: 20
        }
      ],
      isLogin: function() {
        return true;
      }
    }
  });

  require("../../../lib/ccRouter")();

  new cf.view.consoleMenu();

  if (!location.hash) {
    cf.r('data');
  }

}).call(this);

//# sourceMappingURL=main.js.map
