// Generated by CoffeeScript 1.12.7
(function() {
  m.msg = {
    handleListData: function(d) {
      var dd, i, it, j, len, len1, ref, res;
      if (d == null) {
        d = [];
      }
      res = [];
      for (i = 0, len = d.length; i < len; i++) {
        dd = d[i];
        res.push(dd);
        if (dd.reply) {
          ref = dd.reply;
          for (j = 0, len1 = ref.length; j < len1; j++) {
            it = ref[j];
            res.push(it);
          }
        }
      }
      return res;
    }
  };

  module.exports = cf.view.chatPanel = cf.view.collection.extend({
    className: 'chatPanel mobView',
    mode: require('./chatPanel.jade'),
    head: true,
    foot: false,
    tagClass: 'card-block',
    msgEntity: 'msg',
    btmHeight: 8 * 14,
    modelOpt: {
      tmpl: require('./chatItem.jade'),
      className: 'm-b-h'
    },
    events: {
      'click .send': 'send',
      'keyup :input': function(e) {
        if (e.keyCode === 13) {
          return this.send();
        }
      }
    },
    send: function() {
      var d, em, opt, v;
      if (this.ipt == null) {
        this.ipt = this.$('.input');
      }
      v = this.ipt.val();
      if (!v) {
        alert('请先录入信息');
        return;
      }
      d = this.sendData ? this.sendData(v) : {
        user: user.pick(),
        content: this.ipt.val()
      };
      opt = {
        collection: this.collection,
        entity: this.msgEntity,
        _dd: d
      };
      if (this.collection.length) {
        opt.urlRoot = util.actUrl('push', this.msgEntity, '_id', this.collection.at(0).id, 'reply');
      }
      em = new cf.model.entity(d, opt);
      cf.noReply = true;
      em.save(null, {
        success: function(mo) {
          return mo.collection.add(mo._dd);
        }
      });
      this.goBtm();
      return this.ipt.val('');
    },
    goBtm: function() {
      if (this.mb == null) {
        this.mb = this.$('.' + this.tagClass);
      }
      return this.mb.animate({
        scrollTop: this.mb[0].scrollHeight
      }, 500);
    },
    callback: function() {
      this.$el.height($(window).height());
      return this.ctn.height($(window).height() - this.btmHeight);
    },
    afterAddAll: function() {
      return this.goBtm();
    }
  });

}).call(this);

//# sourceMappingURL=app.js.map
