// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    outPut: '/Users/alex/Projects/gameMgr/cmb',
    entry: function(path, lib, bower) {
      return {
        main: [path + 'app/main']
      };
    },
    loaders: function() {
      return [
        {
          test: /\.less$/,
          loader: "style!css!less"
        }, {
          test: /\.css$/,
          loader: 'style-loader!css-loader'
        }, {
          test: /\.jade$/,
          loader: "jade"
        }, {
          test: /\.(png|gif|woff|jpdg|woff2|eot|ttf|svg)$/,
          loader: 'url-loader?limit=1000000'
        }
      ];
    }
  };

}).call(this);

//# sourceMappingURL=webpack.js.map
