// Generated by CoffeeScript 1.12.7
(function() {
  var cat, fcf, i, it, j, len, len1, q, ref, sbar, sns, so, sp, t, title, url;

  require('./style/main.css');

  cf.loadTmpl = function(name) {
    return require("./tmpl/" + name + ".jade");
  };

  cf.loadLibTmpl = function(name) {
    return require("../../../lib/tmpl/" + name + ".jade");
  };

  require('../../../res/js/jquery.tinyscrollbar');

  util.initScroll();

  $('#info').on('click', 'a[data-toggle]', function(e) {
    var t;
    t = util.ct(e);
    return t.parent().addClass('redb').siblings().removeClass('redb');
  });

  ref = $('#info,#extra,#tourListCtn');
  for (i = 0, len = ref.length; i < len; i++) {
    it = ref[i];
    util.initPC(it);
  }

  if ($('.headMenu').length && (cat = util.parseUrl().cat)) {
    $('.headMenu').find("a[href*='" + cat + "']").parent().addClass('active');
  }

  title = $('title').text();

  url = location.href;

  so = [
    {
      code: 'fb',
      url: "http://www.facebook.com/sharer.php?u=" + url + "&t=" + title
    }, {
      code: 'gp',
      url: "http://www.google.com/bookmarks/mark?op=add&bkmk=" + url + "&title=" + title
    }, {
      code: 'tw',
      url: "http://twitter.com/home?status=" + url + " " + title
    }, {
      code: 'email',
      title: 'Send it',
      url: "mailto:?subject=" + title + "&body=" + url
    }
  ];

  if ((sns = $('.sns')).length) {
    for (j = 0, len1 = so.length; j < len1; j++) {
      it = so[j];
      t = it.title || '';
      sns.append("<a title='" + t + "' class='" + it.code + "' href='" + it.url + "' target='_blank'></a>");
    }
  }

  util.addHover = function(t, opt) {
    var o;
    o = $.extend({
      placement: 'right',
      html: true,
      trigger: 'focus',
      template: t.next('.popover')[0].outerHTML
    }, opt || {});
    return t.popover(o);
  };

  sbar = $('.sbar');

  q = sbar.find('#q');

  fcf = sbar.find('.form-control-feedback');

  sp = sbar.find('ul');

  sbar.find('.input-group-btn').hover(function() {
    return sp.show();
  }, function() {
    return sp.hide();
  });

  sbar.on('click', 'li', function(e) {
    t = util.ct(e);
    sbar.find('.et').text(t.text());
    q.data('entity', t.text().toLowerCase());
    sp.hide();
    q[0].blur();
    return q[0].focus();
  });

  q.keyup(function(e) {
    var et;
    t = util.ct(e);
    et = t.data('entity') || 'sight';
    if (e.keyCode === 13) {
      return cf.r("result/" + et + "/" + (t.val()));
    }
  });

  fcf.click(function(e) {
    t = util.ct(e).prev();
    return cf.r("result/" + (t.data('entity') || 'sight') + "/" + (t.val()));
  });

}).call(this);

//# sourceMappingURL=main.js.map
