// Generated by CoffeeScript 1.12.7
(function() {
  var initSelectBtnEvent;

  initSelectBtnEvent = function() {
    var $g_select_btn, $gbox_allgames_subbox, $gbox_history_subbox, $gbox_m, $gbox_tit, $gcbox, $s_select_btn, $sbox_allsvrs_subbox, $sbox_history_subbox, $sbox_m, $sbox_tit, $scbox;
    $g_select_btn = $('#g-select-btn');
    $s_select_btn = $('#s-select-btn');
    $gcbox = $('#g-cbox');
    $scbox = $('#s-cbox');
    $gbox_m = $('#gbox-main');
    $sbox_m = $('#sbox-main');
    $gbox_tit = $('#gbox-tit');
    $sbox_tit = $('#sbox-tit');
    $gbox_allgames_subbox = $('#gbox-allgames-subbox');
    $sbox_allsvrs_subbox = $('#sbox-allsvrs-subbox');
    $gbox_history_subbox = $('#gbox-history-subbox');
    $sbox_history_subbox = $('#sbox-history-subbox');
    $g_select_btn.on('click', function(e) {
      var t;
      if (!$gcbox.hasClass('box-coverbox-show')) {
        $scbox.removeClass('box-coverbox-show');
        $gcbox.addClass('box-coverbox-show');
      } else {
        $gcbox.removeClass('box-coverbox-show');
      }
      if ($gbox_m.hasClass('box-covermain-slided')) {
        $gbox_m.css('height', $gbox_allgames_subbox.height());
      } else {
        $gbox_m.css('height', $gbox_history_subbox.height());
      }
      $gbox_tit.find('.box-coverbox-tit-a').each(function() {
        var $this, s_id;
        $this = $(this);
        s_id = $this.attr('data-scroll');
        if (s_id !== void 0 && s_id !== '') {
          $('#' + s_id).tinyscrollbar();
          $this.attr('data-scroll', '');
        }
      });
      t = 0;
      $gcbox.on('mouseleave', function() {
        var $this;
        clearTimeout(t);
        $this = $(this);
        t = setTimeout((function() {
          $this.removeClass('box-coverbox-show');
          $this.off('mouseleave');
        }), 200);
      }).on('mouseenter', function() {
        clearTimeout(t);
      });
      e.preventDefault();
    });
    $gbox_tit.on('click', '.box-coverbox-tit-a', function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('box-coverbox-tit-a-select')) {
        return;
      } else {
        $gbox_tit.find('.box-coverbox-tit-a-select').removeClass('box-coverbox-tit-a-select');
        $this.addClass('box-coverbox-tit-a-select');
        if (!$gbox_m.hasClass('box-covermain-animate')) {
          $gbox_m.addClass('box-covermain-animate');
        }
        if ($gbox_m.hasClass('box-covermain-slided')) {
          $gbox_m.removeClass('box-covermain-slided');
          $gbox_m.css('height', $gbox_history_subbox.height());
        } else {
          $gbox_m.addClass('box-covermain-slided');
          $gbox_m.css('height', $gbox_allgames_subbox.height());
        }
      }
    });
    $s_select_btn.on('click', function(e) {
      var t, webgame_id;
      webgame_id = $g_select_btn.attr('data-gid');
      if (webgame_id === void 0 || webgame_id === '') {
        $g_select_btn.ktip('<span class="red">请先选择需要充值的游戏</span>', {
          direction: 'left',
          offset: 18,
          atX: -5,
          atY: 19,
          closeBtn: false,
          stick: 2000
        });
        return;
      }
      if (!$scbox.hasClass('box-coverbox-show')) {
        $gcbox.removeClass('box-coverbox-show');
        $scbox.addClass('box-coverbox-show');
      } else {
        $scbox.removeClass('box-coverbox-show');
      }
      if ($sbox_m.hasClass('box-covermain-slided')) {
        $sbox_m.css('height', $sbox_allsvrs_subbox.height());
      } else {
        $sbox_m.css('height', $sbox_history_subbox.height());
      }
      $sbox_tit.find('.box-coverbox-tit-a').each(function() {
        var $this, s_id;
        $this = $(this);
        s_id = $this.attr('data-scroll');
        if (s_id !== void 0 && s_id !== '') {
          $('#' + s_id).tinyscrollbar();
          $this.attr('data-scroll', '');
        }
      });
      t = 0;
      $scbox.on('mouseleave', function() {
        var $this;
        clearTimeout(t);
        $this = $(this);
        t = setTimeout((function() {
          $this.removeClass('box-coverbox-show');
          $this.off('mouseleave');
        }), 200);
      }).on('mouseenter', function() {
        clearTimeout(t);
      });
    });
    $sbox_tit.on('click', '.box-coverbox-tit-a', function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('box-coverbox-tit-a-select')) {
        return;
      } else {
        $sbox_tit.find('.box-coverbox-tit-a-select').removeClass('box-coverbox-tit-a-select');
        $this.addClass('box-coverbox-tit-a-select');
        if (!$sbox_m.hasClass('box-covermain-animate')) {
          $sbox_m.addClass('box-covermain-animate');
        }
        if ($sbox_m.hasClass('box-covermain-slided')) {
          $sbox_m.removeClass('box-covermain-slided');
          $sbox_m.css('height', $sbox_history_subbox.height());
        } else {
          $sbox_m.addClass('box-covermain-slided');
          $sbox_m.css('height', $sbox_allsvrs_subbox.height());
        }
      }
    });
    $gbox_m.on('click', '.box-coverbox-list-a', function(e) {
      var all_games, gid, id;
      e.preventDefault();
      id = $(this).attr('data-id');
      all_games = games;
      try {
        gid = all_games[id].webgame_id;
        $g_select_btn.attr('data-gid', gid).html(all_games[id].name);
        $gcbox.removeClass('box-coverbox-show');
        gameinfo['g'] = gid;
        refreshSidSelectBtn();
      } catch (error) {
        e = error;
      }
    });
    $sbox_m.on('click', '.box-coverbox-list-a', function() {
      var $this, sid;
      $this = $(this);
      sid = $this.attr('data-sid');
      $s_select_btn.attr('data-sid', sid).html($this.html());
      $scbox.removeClass('box-coverbox-show');
      gameinfo['s'] = sid;
    });
  };

}).call(this);

//# sourceMappingURL=common.js.map
