// Generated by CoffeeScript 1.12.7
(function() {
  require('./style/mob.css');

  $.extend(cf, {
    loadTmpl: function(name) {
      return require("./tmpl/" + name + ".jade");
    },
    loadLibTmpl: function(name) {
      return require("../../../lib/tmpl/" + name + ".jade");
    },
    _init: function() {
      require('../../../lib/meta/content');
      require('../../../lib/func/entityAction');
      require('../../../lib/view/collection/app');
      require('../../../lib/view/collection/table');
      require('../../../lib/view/collection/jsonTable');
      require('../../../lib/widget/refFileCollection');
      require('../../../lib/widget/editor/dTime');
      return require('../../../lib/widget/editor/selectBox/multiSelect');
    }
  });

  require("../../../lib/mobRouter")();

  require("./mod/home")();

}).call(this);

//# sourceMappingURL=mob.js.map
