// Generated by CoffeeScript 1.12.7
(function() {
  var pl;

  require('./style/main.css');

  require('../../../lib/main');

  cf.loadTmpl = function(name) {
    return require("./" + name + ".jade");
  };

  cf.loadLibTmpl = function(name) {
    return require("../../../lib/tmpl/" + name + ".jade");
  };

  require('../../../res/js/jquery.tinyscrollbar');

  require('../../../res/js/fullpage.js/jquery.fullPage');

  require('../../../res/js/fullpage.js/jquery.fullPage.css');

  require('../plugin/countdown/jcountdown.css');

  require('../plugin/countdown/index.css');

  require('../plugin/countdown/jquery.jcountdown.min');

  require('../../../../ext/string');

  require('../../../lib/view/sForm');

  W.meta = require('../../../lib/meta/common');

  require('./meta/application');

  new cf.view.sForm({
    entity: 'application',
    el: '#regForm',
    toFetch: false,
    validForm: function() {
      var rt;
      rt = $('#isAccept').is(':checked');
      if (!rt) {
        alert('请先阅读免责声明');
      }
      return rt;
    },
    _saveSuccess: function(model, res) {
      if (true) {
        alert('报名成功');
        return model.view.reset();
      } else {
        return alert('请不要重复报名');
      }
    }
  });

  $('#scrollBox').fullpage({
    anchors: ['home', 'news', 'register', 'events', 'about'],
    menu: '#menu',
    loopBottom: true,
    afterLoad: function() {
      return util.loadPic();
    }
  });

  $("#timerContent .countdown").jCountdown({
    timeText: $('body').attr('et').replaceAll('-', '/'),
    style: "flip",
    color: "white"
  });

  $('.imgs-banner-mud img').click(function(e) {
    return util.setActive(e);
  });

  pl = $('#videoPlayer');

  $('.videos li').click(function(e) {
    var t, url;
    t = util.ct(e);
    url = t.data('url');
    return pl.empty().append("<embed autoplay='autoplay' src='" + url + "' allowFullScreen='true' quality='high' width='770' height='500' align='middle' allowScriptAccess='always' type='application/x-shockwave-flash'/>");
  });

  $('.videos li:eq(0)').trigger('click');

}).call(this);

//# sourceMappingURL=main.js.map
