// Generated by CoffeeScript 1.12.7
(function() {
  m.course = {
    prop: [_ep('title'), _ep('subTitle'), _ep('brief'), _ep('content:content'), m._pic('head'), m._pic('slide'), m.content.prop.codeBy('status')]
  };

}).call(this);

//# sourceMappingURL=course.js.map
