// Generated by CoffeeScript 1.12.7
(function() {
  var animEndEventName, animEndEventNames, onEndAnimation, support;

  support = {
    animations: Modernizr.cssanimations
  };

  animEndEventNames = {
    'WebkitAnimation': 'webkitAnimationEnd',
    'OAnimation': 'oAnimationEnd',
    'msAnimation': 'MSAnimationEnd',
    'animation': 'animationend'
  };

  animEndEventName = animEndEventNames[Modernizr.prefixed('animation')];

  onEndAnimation = function(el, callback, animEndEventName) {
    var onEndCallbackFn;
    if (animEndEventName == null) {
      animEndEventName = 'webkitAnimationEnd';
    }
    onEndCallbackFn = function(ev) {
      if (support.animations) {
        if (ev.target !== this) {
          return;
        }
        this.removeEventListener(animEndEventName, onEndCallbackFn);
      }
      if (callback && typeof callback === 'function') {
        return callback.call();
      }
    };
    if (support.animations) {
      return el.addEventListener(animEndEventName, onEndCallbackFn);
    } else {
      return onEndCallbackFn();
    }
  };

}).call(this);

//# sourceMappingURL=animation.js.map
