// Generated by CoffeeScript 1.12.7
(function() {
  var op;

  op = {
    id: "go-top",
    title: "返回顶部"
  };

  cf.bbEvt.on('scroll', function() {
    if (window.scrollY > 200) {
      if (!cf.noGoTop && !$('#go-top').length) {
        return $('body').mk('span', op, null, null, null, function() {
          util.sTop(null, 55, 500);
          return $(this).remove();
        });
      }
    } else {
      return $('#go-top').remove();
    }
  });

}).call(this);

//# sourceMappingURL=goTop.js.map
