// Generated by CoffeeScript 1.12.7
(function() {
  var metaOpt;

  metaOpt = m._;

  $.extend(metaOpt.btn, {
    popEdit: function(it, e) {
      return util.iBtn('edit', 'popEdit');
    },
    popAdd: function() {
      return util.tBtn('add', null, 'plus', 'popAdd btn btn-primary btn-sm');
    },
    popView: function(it, e) {
      return util.iBtn("list-alt", 'edit');
    }
  });

  $.extend(metaOpt.event, {
    popEdit: {
      type: 'click',
      fun: function(e) {
        var id, md, opt;
        md = this.findData(e);
        opt = {
          toFetch: false,
          rCollection: this.collection,
          btns: ['save']
        };
        if (this.formOpt) {
          $.extend(opt, _.result(this, 'formOpt'));
        }
        if (this.formEditOpt) {
          $.extend(opt, _.result(this, 'formEditOpt'));
        }
        id = null;
        if (opt.toFetch) {
          opt.listenTime = 'listenToOnce';
          id = md.id;
        } else {
          opt.model = md;
        }
        app.dm.edit('air', this.entity, id, opt);
        return util.esp(e);
      }
    },
    popAdd: {
      type: 'click',
      fun: function(e) {
        var opt;
        opt = {
          entity: this.entity,
          toFetch: false,
          rCollection: this.collection,
          btns: ['save']
        };
        if (!this.data && this.meta.initData) {
          this.data = this.meta.initData.call(this);
        }
        if (this.formOpt) {
          $.extend(opt, _.result(this, 'formOpt'));
        }
        if (this.formAddOpt) {
          $.extend(opt, _.result(this, 'formAddOpt'));
        }
        app.dm.add('air', this.entity, opt);
        return util.esp(e);
      }
    },
    popView: {
      type: 'click',
      fun: function(e) {
        var d, opt;
        d = this.findData(e);
        opt = {
          model: d,
          title: iim('view', this.entity),
          foot: false
        };
        if (this.viewOpt) {
          $.extend(opt, _.result(this, 'viewOpt'));
        }
        return app.dm.view('air', this.entity, d.id, opt);
      }
    }
  });

}).call(this);

//# sourceMappingURL=popBtn.js.map
