// Generated by CoffeeScript 1.12.7
(function() {
  var metaOpt;

  module.exports = cf.view.showInTd = function(e) {
    var pt, ptr, t, tr;
    t = util.ct(e);
    pt = t.parent().is('td') ? 'tr' : '.list-group-item';
    ptr = t.closest(pt);
    if (t.children().hasClass('glyphicon-plus')) {
      t.children().toggleClass('glyphicon-minus');
    }
    if (t.hasClass('active')) {
      ptr.removeClass('hasSubTable').next().remove();
    } else {
      if (ptr.hasClass('hasSubTable')) {
        tr = ptr.next();
        tr.children('td').empty();
        t.siblings().removeClass('active');
      } else {
        tr = t.parent().is('td') ? $("<tr class='subTable'><td colspan=\"" + (ptr.children('td').length) + "\"></td></tr>") : $('<div><div></div></div>');
        ptr.addClass('hasSubTable').after(tr);
      }
      if (typeof this.afterShow === "function") {
        this.afterShow(e, tr.children());
      }
    }
    t.toggleClass('active');
    return e.stopPropagation();
  };

  metaOpt = m._;

  $.extend(metaOpt.btn, {
    showInTd: function(it) {
      return util.iBtn("plus", 'showInTd');
    }
  });

  $.extend(metaOpt.event, {
    showInTd: {
      type: 'click',
      fun: cf.view.showInTd
    }
  });

}).call(this);

//# sourceMappingURL=showInTd.js.map
