// Generated by CoffeeScript 1.12.7
(function() {
  window.io = require("socket.io");

  cf.onMap = {};

  window.se = function(path, opt, f) {
    log('emit: ' + path);
    log(opt);
    log('end...');
    return st.emit(path, opt, f);
  };

  window.so = function(path, cb) {
    if (cf.onMap[path]) {
      return;
    }
    cf.onMap[path] = true;
    return st.on(path, function(d) {
      log('listen: ' + path);
      return cb(d);
    });
  };

  module.exports = function(code) {
    return window.st = code ? io("/" + code) : io();
  };

}).call(this);

//# sourceMappingURL=socket.js.map
