// Generated by CoffeeScript 1.12.7
(function() {
  var lg, loginTmpl;

  lg = require('../widget/login');

  loginTmpl = require('./webLoginTmpl.jade');

  module.exports = {
    routes: {
      '!/login': 'login',
      '!/reg(:/param)': 'reg'
    },
    reg: function(p) {
      this.ctn.html(cf.rtp(loginTmpl, {
        pic: 'reg.png'
      }));
      return lg.regForm('#logReg', {
        className: 'break',
        style: 'panel-primary',
        saveSuccess: function() {
          return cf.r('login');
        },
        callback: function() {
          return this.ctn.append($('#loginPart').removeClass('hidden'));
        }
      });
    },
    login: function() {
      this.ctn.html(cf.rtp(loginTmpl, {
        pic: 'login.png'
      }));
      return lg.loginForm('#logReg', {
        cleanAll: true,
        asterisk: false,
        className: 'break',
        style: 'panel-primary',
        callback: function() {
          return this.ctn.append($('#loginPart').removeClass('hidden'));
        }
      });
    },
    _app: {
      noAuthPage: ['login', 'reg'],
      _mod_ctn: '#main',
      account: function() {
        return lg.changePsdForm('air');
      }
    }
  };

}).call(this);

//# sourceMappingURL=webLogin.js.map
