// Generated by CoffeeScript 1.12.7
(function() {
  m.courseContent = {
    prop: [_ep('title'), _ep('row'), m._textarea('课程介绍')]
  };

  m.course = {
    prop: [
      _ep('title'), _ep('subTitle'), _ep('description'), m._itemTable('courseContent', {
        label: '课程内容'
      }), _ep('price'), m._cat('course'), m._pic('head'), m.content.prop.codeBy('status')
    ]
  };

}).call(this);

//# sourceMappingURL=course.js.map
