// Generated by CoffeeScript 1.12.7
(function() {
  var _end, _qFun, _start, ptt;

  require('../../../../lib/terminal/tf/dTime');

  ptt = function(v) {
    return v + "%";
  };

  _start = {
    title: '开始时间',
    type: 'text',
    xtype: 'dTime',
    attrs: {
      minView: 2,
      fmt: 'yyyy-mm-dd',
      val: new Date().pattern('yyyy-MM-dd')
    }
  };

  _end = {
    title: '结束时间',
    type: 'text',
    xtype: 'dTime',
    attrs: {
      minView: 2,
      fmt: 'yyyy-mm-dd',
      val: new Date().addDays(1).pattern('yyyy-MM-dd')
    }
  };

  _qFun = function(e) {
    var c, end, start, toolbar;
    c = this.collection;
    toolbar = this.$('.toolbar');
    start = toolbar.find("[placeholder='开始时间']").val();
    end = toolbar.find("[placeholder='结束时间']").val();
    c.criteria = {
      max: 15,
      q: {
        start: start,
        end: end
      }
    };
    return c.resetFetch();
  };

  m.pay = {
    label: '充值列表',
    prop: [
      _ep('game', {
        label: '游戏'
      }), _ep('uid', {
        label: '用户ID'
      }), _ep('username', {
        label: '用户名'
      }), _ep('pay_time', {
        label: '充值时间'
      }), _ep('pay_money', {
        label: '充值金额'
      }), _ep('channel', {
        label: '充值渠道'
      })
    ],
    listOpt: {
      btns: [],
      itemBtns: [],
      colNum: 6,
      events: {
        'click .toolbar .sh': _qFun
      }
    },
    filter: {
      start: _start,
      end: _end,
      btn: {
        type: 'btn',
        cls: cf.btnStr + ' sh',
        label: '搜索'
      }
    }
  };

  m.channel = {
    label: '渠道总报',
    prop: [
      _ep('day', {
        label: '日期'
      }), _ep('fcode', {
        label: '渠道'
      }), _ep('dau', {
        label: 'DAU'
      }), _ep('uv', {
        label: 'UV'
      }), _ep('pv', {
        label: 'PV'
      }), _ep('login_count', {
        label: '登陆用户数'
      }), _ep('nregister_count', {
        label: '新注册用户数'
      }), _ep('register_rate', {
        label: '注册转化率',
        showText: ptt
      }), _ep('register_retained', {
        label: '次日留存率',
        showText: ptt
      }), _ep('pay_count', {
        label: '充值人数'
      }), _ep('pay_money', {
        label: '充值金额'
      }), _ep('pay_rate', {
        label: '付费率',
        showText: ptt
      }), _ep('register_pay_count', {
        label: '新注册用户充值人数'
      }), _ep('register_pay_money', {
        label: '新注册用户充值金额'
      }), _ep('register_pay_rate', {
        label: '新增付费率',
        showText: ptt
      }), _ep('arpu', {
        label: 'ARPU'
      }), _ep('arppu', {
        label: 'ARPPU'
      })
    ],
    listOpt: {
      colNum: 17,
      btns: [],
      itemBtns: [],
      events: {
        'click .toolbar .sh': _qFun,
        'click .week': function(e) {
          return $.get(util.restUrl('channelWeek'), (function(_this) {
            return function(res) {
              return _this.collection.reset(res.entities);
            };
          })(this));
        },
        'click .month': function(e) {
          return $.get(util.restUrl('channelMonth'), (function(_this) {
            return function(res) {
              return _this.collection.reset(res.entities);
            };
          })(this));
        },
        'change ._datetime': function(e) {
          var dd, end, start, tt, url;
          dd = this.$('._datetime');
          start = dd.eq(0).val();
          end = dd.eq(1).val();
          url = util.getUrlParams(util.restUrl('exportChannelData'), {
            "q[start]": start,
            "q[end]": end
          });
          tt = this.$('.exData');
          return tt.attr('href', url);
        }
      }
    },
    filter: {
      start: _start,
      end: _end,
      btn: {
        type: 'btn',
        cls: cf.btnStr + ' sh',
        label: '搜索'
      },
      "export": {
        type: 'btn',
        label: '导出数据',
        href: util.restUrl('exportChannelData'),
        cls: cf.btnStr + ' exData'
      },
      week: {
        type: 'btn',
        label: '一周数据',
        cls: cf.btnStr + ' week'
      },
      month: {
        type: 'btn',
        label: '一个月数据',
        cls: cf.btnStr + ' month'
      }
    }
  };

}).call(this);

//# sourceMappingURL=meta.js.map
