// Generated by CoffeeScript 1.12.7
(function() {
  meta.bizText = {
    code: {
      type: 'text'
    },
    text: {
      type: 'textarea',
      rows: 4
    },
    type: {
      type: 'select',
      data: ['短信']
    },
    _: {
      tbItem: {
        code: {
          w: 120
        },
        type: {
          w: 100
        },
        text: {
          type: 'text'
        },
        _btn: ['popEdit', 'del']
      },
      item: ['code', 'type', 'text']
    }
  };

}).call(this);

//# sourceMappingURL=bizText.js.map
