// Generated by CoffeeScript 1.12.7
(function() {
  m.link = {
    code: 'link',
    def: true,
    type: 'entity',
    prop: [_ep('title'), _ep('row'), _ep('href'), _ep('description'), _ep('pic'), _ep('url')]
  };

}).call(this);

//# sourceMappingURL=link.js.map
