// Generated by CoffeeScript 1.12.7
(function() {
  meta.membership = {
    prop: [
      {
        code: 'uid',
        type: 'text',
        xtype: 'selectBox',
        bind: true,
        attrs: {
          label: 'username',
          showImg: 'portrait',
          hiddenValue: true,
          searchItem: 'username',
          setAttrs: 'username',
          setToEntity: true,
          panelOpt: {
            entity: 'user',
            noStr: 'Search User by username or Email'
          }
        }
      }, _ep('row'), m._radio('isAccept'), _ep('description')
    ]
  };

}).call(this);

//# sourceMappingURL=membership.js.map
