// Generated by CoffeeScript 1.12.7
(function() {
  var showInTd;

  showInTd = require("../func/showInTd");

  meta.org = {
    prop: [
      m._select('pid', {
        label: '父机构',
        attrs: {
          entity: 'org',
          keyVal: 'id,title'
        }
      }), m._select('type', {
        attrs: {
          data: {
            1: '内部',
            2: '外部'
          }
        }
      }), _ep('title'), _ep('description')
    ],
    btn: {
      showInTd: function() {
        return util.iBtn("user", 'showInTd');
      }
    }
  };

  meta.orgRelation = {
    prop: [
      _ep('uid'), _ep('row'), _ep('description'), m._select('role', {
        attrs: {
          data: {
            master: '站长',
            worker: '师傅',
            operator: '资料员',
            partner: '物业经理'
          }
        }
      })
    ],
    btn: {
      user: function(it, e) {
        return util.tBtn('edit', util.navUrl(e, 'edit', it.rid, it.id), 'edit');
      }
    }
  };

}).call(this);

//# sourceMappingURL=org.js.map
