// Generated by CoffeeScript 1.12.7
(function() {
  meta.partner = {
    prop: [_ep('title'), m._text('slogan'), _ep('phone'), _ep('contact'), _ep('introduction'), _ep('url'), m._pic('id'), m._pic('qrcode')]
  };

}).call(this);

//# sourceMappingURL=partner.js.map
