// Generated by CoffeeScript 1.12.7
(function() {
  m.roleMap = {
    prop: [
      _ep('code'), _ep('role'), m._number('total', {
        val: 0
      }), m._number('left', {
        val: 0
      }), _ep('description')
    ],
    _: {}
  };

}).call(this);

//# sourceMappingURL=roleMap.js.map
