// Generated by CoffeeScript 1.12.7
(function() {
  m.video = {
    prop: [
      _ep('title', {
        valid: {
          require: true
        }
      }), _ep('cat'), _ep('url', {
        valid: {
          require: true,
          url: true
        }
      }), _ep('description')
    ]
  };

}).call(this);

//# sourceMappingURL=video.js.map
