// Generated by CoffeeScript 1.12.7
(function() {
  var b, c;

  b = require('../../../lib/i18n/zh');

  c = require('./server_zh');

  $.extend(window, {
    _i: $.extend(b, c, {
      vote: '投票',
      count: '投票数',
      giftCode: '礼品码'
    }),
    _lang: 'zh'
  });

}).call(this);

//# sourceMappingURL=zh.js.map
