// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    outPut: '/Users/alex/Projects/gameMgr/cmb',
    entry: function(path, lib, bower) {
      return {
        main: [path + 'app/main']
      };
    },
    noLang: true,
    jq: '11'
  };

}).call(this);

//# sourceMappingURL=webpack.js.map
