// Generated by CoffeeScript 1.12.7
(function() {
  var c;

  require('./zh');

  c = require('../../console/i18n/zh');

  $.extend(window._i, c);

}).call(this);

//# sourceMappingURL=console_zh.js.map
