// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = _exv('sideMenu', '_tag', {
    tmpl: require('./tmpl.jade'),
    parent: '#content',
    cleanAll: true,
    data: {},
    render: function() {
      return this.$("[href='" + location.hash + "']").parent().addClass('active');
    },
    init: function() {
      return this.listenTo(user, 'logout', (function(_this) {
        return function() {
          return _this._close();
        };
      })(this));
    },
    events: {
      'click li': function(e) {
        util.setActive(e);
        return typeof this.afterClick === "function" ? this.afterClick() : void 0;
      }
    }
  });

}).call(this);

//# sourceMappingURL=app.js.map
