// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    task: '打卡',
    work: '成就',
    memo: '备忘',
    newest: '最新',
    rank: '看榜',
    top: '置顶',
    pop: '人气',
    kind: '贡献',
    favorite: '收藏',
    setting: '设置',
    thread: '帖子',
    members: '小组成员',
    member: '小伙伴',
    workYear: '工作时间',
    organizer: '发起人',
    oper: '管理员',
    userCenter: '个人中心',
    generalInfo: '基本信息',
    applicationInfo: '申请信息',
    m_timeStr: '第{}周 共{}周 开始于{}',
    m_member: '成员 <span class="mCount">{}</span>人',
    m_post: '帖子 <span class="mThread">{}</span>篇',
    m_fee: '经费 <span class="mFee">{}</span>元',
    m_member_tip: '以下信息只是组内可见, 请选择性填写!',
    groupNameCard: '组名片'
  };

}).call(this);

//# sourceMappingURL=zh.js.map
