// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    console: 'Console',
    m_select: 'Select {}',
    m_mgm: 'Mgm {}',
    m_base: 'Base {}',
    m_biz: 'Biz {}',
    m_menu: '{} Menu',
    m_enrol_ok: '您已经成功报名了。',
    m_enrol_f: '对不起，您已经报过名了！'
  };

}).call(this);

//# sourceMappingURL=en.js.map
