// Generated by CoffeeScript 1.12.7
(function() {
  var initEditor, sn;

  require('./snBtn');

  initEditor = function(opt) {
    var editor, ipp, p, sopt, t;
    if (opt.type == null) {
      opt.type = 'full';
    }
    p = $(opt.parent);
    $.extend($.summernote.plugins, cf._snPlugin);
    t = p.find('textarea');
    sopt = {
      placeholder: opt.ph,
      height: opt.height || 300,
      lang: opt.lang,
      focus: true,
      codemirror: {
        theme: 'monokai'
      },
      toolbar: sn.btns(opt.type)
    };
    if (user.isAdmin() && !cf.view.content.added) {
      ipp = sopt.toolbar[3][1];
      if (ipp) {
        ipp.concatBy(['item', 'tmpl', 'custContent']);
      }
      sopt.toolbar.push(['misc', ['codeview', 'fullscreen']]);
      cf.view.content.added = true;
    }
    if (cf.mob) {
      sopt.height = window.innerHeight - 250;
      sopt.toolbar = sn[opt.type];
    }
    editor = t.summernote(sopt);
    if (t.val()) {
      editor.summernote('code', t.val());
    } else {
      editor.summernote('code', '');
    }
    return opt.form._snote[opt.name] = editor;
  };

  sn = cf.view.content = {
    full: [['easy', ['text']], ['font', ['style', 'bold', 'italic', 'underline', 'strikethrough', 'clear', 'fontsize', 'color', 'height']], ['para', ['ul', 'ol', 'paragraph']], ['insert', ['hr', 'link', 'video', 'table', 'pic']]],
    simple: [['mob', ['paragraph', 'ul', 'bold', 'style', 'link', 'pic', 'table']]],
    btns: function(type) {
      return cf.view.content[type];
    },
    fun: function(opt) {
      util.lcss(cf.rPath + "js/summernote/dist/summernote.css");
      return cf.loadJS(cf.rPath + 'js/summernote/dist/summernote.js', function() {
        if (_lang === 'zh') {
          opt.lang = 'zh-CN';
          return cf.loadJS(cf.rPath + 'js/summernote/lang/summernote-zh-CN.js', function() {
            return initEditor(opt);
          });
        } else {
          return initEditor(opt);
        }
      });
    }
  };

  m._summer = function(code, opt) {
    return $.extend(true, {
      code: code,
      type: 'textarea',
      xtype: 'content',
      attrs: {
        rows: 16
      }
    }, opt);
  };

  module.exports = sn;

}).call(this);

//# sourceMappingURL=app.js.map
