// Generated by CoffeeScript 1.12.7
(function() {
  var i, k, len, ro;

  require('../../../../lib/widget/editor/rating/app');

  m.rating = {
    prop: [
      _ep('firstName'), _ep('lastName'), _ep('email'), _ep('guideName', {
        col: 6
      }), m._tag('hr'), m._textarea('content', {
        label: 'Do you have any other comments or suggestion?'
      })
    ]
  };

  ro = ['tourArrangement', 'guideAttitude', 'guideService', 'guideCompetence', 'vehicleCondition', 'drivingSkill', 'foodQuality', 'overallEvaluation'];

  for (i = 0, len = ro.length; i < len; i++) {
    k = ro[i];
    m.rating.prop.push({
      code: k,
      xtype: 'raiting',
      attrs: {
        rateable: true
      }
    });
  }

}).call(this);

//# sourceMappingURL=rating.js.map
