// Generated by CoffeeScript 1.12.7
(function() {
  require('../meta/membership');

  module.exports = cf.view.collection.extend({
    entity: 'membership',
    toFetch: true,
    init: function() {
      this.res = [];
      return $(this.parent).addClass('pickAvator');
    },
    events: {
      'click img': 'pickImg'
    },
    pickImg: function(e) {
      var d, t;
      t = util.ct(e);
      d = this.collection.get(util.getTargetId(e)).attributes;
      if (t.hasClass('active')) {
        t.removeClass('active');
        this.targetInput.find(".c-" + d.id).remove();
        this.res.remove(d.user.id + "-" + d.user.username);
      } else {
        t.addClass('active');
        this.targetInput.append("<span class='c-" + d.id + "'>" + d.user.username + "</span>");
        this.res.push(d.user.id + "-" + d.user.username);
      }
      return this.form.model.set('tutor', this.res.join(','));
    },
    criteriaOpt: function() {
      return {
        _attrs: 'user:username__email__introduction__refFile'
      };
    },
    addAll: function() {
      var d, i, len, ref, results, u;
      ref = this.data;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        d = ref[i];
        results.push(u = d.user);
      }
      return results;
    },
    callback: function() {
      this.targetInput = $('<div class="picked"></div>');
      return $(this.parent).append(this.targetInput);
    }
  });

}).call(this);

//# sourceMappingURL=selectUser.js.map
