// Generated by CoffeeScript 1.12.7
(function() {
  Backbone.getSyncMethod = function(model, op) {
    var co, mo;
    if (op.forceSync) {
      return Backbone[op.forceSync];
    }
    mo = model;
    co = model.collection;
    if (mo.stSync || (co && co.stSync)) {
      return Backbone.stSync;
    } else if (mo.localSync || co.localSync) {
      return Backbone.localStorage;
    } else {
      return Backbone.sync;
    }
  };

  Backbone.sync = function(method, model, options) {
    return Backbone.getSyncMethod(model, options).apply(this, [method, model, options]);
  };

}).call(this);

//# sourceMappingURL=BBSync.js.map
