// Generated by CoffeeScript 1.12.7
(function() {
  var i, it, len, ref;

  require('../../../../lib/func/ipBtn');

  m.forumPost = {
    label: '论坛帖子',
    prop: [_ep('title'), m._cat('forumPost'), _ep('brief'), _ep('content:content')],
    listOpt: {
      criteriaOpt: function() {
        return {
          q: {
            'user._id': user.id
          }
        };
      }
    }
  };

  m.post = {
    label: '文章',
    prop: [_ep('title'), m._cat('forumPost'), _ep('brief'), _ep('content:content')],
    listOpt: {
      criteriaOpt: function() {
        return {
          q: {
            'user._id': user.id
          }
        };
      }
    }
  };

  m.myCourse = {
    label: '我的课程',
    prop: []
  };

  ref = ['forumPost', 'post', 'myCourse'];
  for (i = 0, len = ref.length; i < len; i++) {
    it = ref[i];
    cf.view.ipBtn('home', it, ctn, {
      func: 'tb'
    });
  }

}).call(this);

//# sourceMappingURL=home.js.map
