// Generated by CoffeeScript 1.12.7
(function() {
  var router, webUser;

  router = require("../../../lib/userRouter");

  webUser = require('../../../lib/model/webUser');

  require('../../../lib/widget/slide/app');

  window.user = new webUser({}, {
    check: function() {
      return true;
    }
  });

  new router({
    _exr: [require('../../../lib/func/webLogin')],
    checkAuth: true
  });

}).call(this);

//# sourceMappingURL=router.js.map
