// Generated by CoffeeScript 1.12.7
(function() {
  var mb;

  require('../../public/res/js/jquery.finger/dist/jquery.finger');

  require('../../public/res/js/fastclick/lib/fastclick').attach(document.body);

  mb = $('#menuBtn');

  $('#nav').on('click', "a[href^='#!'],a[onclick]", function() {
    return mb.trigger('click');
  });

  cf.view.form.prototype.btns = ['save'];

  cf.view.form.prototype.cols = 'col-xs-3:col-xs-9';

  cf.view.form.prototype.colon = false;

  cf.view.tag.prototype.backBtn = true;

  cf.view.tag.prototype.fullScreen = true;

  cf.view.tag.prototype.closeBtn = true;

  cf._initOpt = function(k) {
    var op, opt;
    opt = {
      className: 'mobView',
      mode: 'panel',
      style: "panel-primary",
      head: true,
      cleanAll: true
    };
    if (k === 'list') {
      op = {
        noFilter: true
      };
    }
    return $.extend(opt, op);
  };

}).call(this);

//# sourceMappingURL=mob.js.map
