// Generated by CoffeeScript 1.12.7
(function() {
  var _slide, oll;

  require('../../public/res/js/jquery.finger/dist/jquery.finger');

  require('../../public/res/js/fastclick/lib/fastclick').attach(document.body);

  _slide = require('./func/pageSlider/_slide');

  _st.mode = 'card';

  _st.labelCls = 'form-control-label';

  cf.view.tag.prototype.className = 'mobView';

  cf.view.form.prototype.mode = _st.mode;

  cf.view.form.prototype.className = 'breakForm mobView';

  cf.view.form.prototype.btns = ['save'];

  cf.view.form.prototype.cols = 'col-xs-3:col-xs-9';

  cf.view.form.prototype.colon = false;

  cf.view.form.prototype.focus = false;

  cf.view.tag.prototype.backBtn = true;

  cf.view.tag.prototype.fullScreen = true;

  oll = cf.dm.l;

  cf.dm.l = function(cp, place, opt) {
    if (place === 'slide') {
      opt.render = _slide;
    }
    return oll.apply(app, arguments);
  };

  cf._initOpt = function() {
    return {
      mode: _st.mode,
      head: true,
      cleanAll: true
    };
  };

}).call(this);

//# sourceMappingURL=mobv2.js.map
