// Generated by CoffeeScript 1.12.7
(function() {
  var router, uu;

  router = require('./userRouter').extend({
    _exr: [require('./func/webLogin')]
  });

  uu = require('./model/user');

  require('./terminal/h5');

  require('./terminal/h5_ft_login');

  W.ctn = $('#main');

  cf._uOpt = $.extend({
    afterLogin: function() {
      if (this.hasRole('admin')) {
        this.logout();
        return;
      }
      new cf.view.sideMenu();
      return W.ctn = '#main';
    },
    check: function() {
      return true;
    }
  }, cf._uOpt);

  cf._rOpt = $.extend({
    checkAuth: true,
    logoutPath: util.navUrl('login')
  }, cf._rOpt);

  module.exports = function() {
    if (typeof cf._init === "function") {
      cf._init();
    }
    W.user = new uu(cf._uData, cf._uOpt);
    new router(cf._rOpt);
    return app.menu = new cf.view.topMenu(cf._topOpt);
  };

}).call(this);

//# sourceMappingURL=webRouter.js.map
