// Generated by CoffeeScript 1.12.7
(function() {
  require('./style/main.css');

  cf.loadTmpl = function(name) {
    return require("./tmpl/" + name + ".jade");
  };

  cf.loadLibTmpl = function(name) {
    return require("../../../lib/tmpl/" + name + ".jade");
  };

  cf._uOpt = {
    check: function() {
      return true;
    },
    afterLogin: function() {
      return new cf.view.sideMenu();
    }
  };

  require("../../../lib/webRouter")();

}).call(this);

//# sourceMappingURL=main.js.map
