// Generated by CoffeeScript 1.12.7
(function() {
  require('./style.sass');

  module.exports = _exv('topMenu', '_tag', {
    dep: true,
    className: 'nav navbar-nav pull-right',
    parent: '#topBar',
    tagName: 'ul',
    auto: false,
    data: {},
    initMenu: [
      {
        key: 'login',
        icon: 'log-in'
      }, {
        key: 'reg',
        icon: 'user'
      }
    ],
    events: {
      'click li': function(e) {
        util.setActive(e);
        return typeof this.afterClick === "function" ? this.afterClick() : void 0;
      }
    },
    render: function() {
      this.ctn.empty().append(cf.rtp(require('./tmpl.jade'), this.data));
      return this.initActive();
    },
    afterLogout: function() {
      return this.setMenu(this.initMenu);
    },
    afterLogin: function() {
      return this.setMenu([
        {
          label: user.username,
          avatar: true,
          children: user._func.children
        }
      ]);
    },
    init: function() {
      if (this.dep) {
        this.listenTo(user, 'login', (function(_this) {
          return function() {
            return _this.afterLogin();
          };
        })(this));
        this.listenTo(user, 'logout', (function(_this) {
          return function() {
            return _this.afterLogout();
          };
        })(this));
        return user.trigger(user.isLogin() ? 'login' : 'logout');
      }
    },
    initActive: function() {
      return this.$("[href='" + location.hash + "']").parent().addClass('active');
    },
    setMenu: function(data) {
      this.data.menus = data;
      return this.render();
    }
  });

}).call(this);

//# sourceMappingURL=app.js.map
