// Generated by CoffeeScript 1.12.7
(function() {
  require('./app');

  module.exports = _exv('consoleMenu', 'topMenu', {
    initMenu: [],
    preLogin: function() {
      return this.ctn.empty();
    },
    parent: '#ubb',
    className: 'nav navbar-nav col-xs-12',
    afterLogin: function() {
      return this.setMenu(user.setMenu(this.home, this.funcMenu));
    }
  });

}).call(this);

//# sourceMappingURL=consoleMenu.js.map
