// Generated by CoffeeScript 1.12.7
(function() {
  var b, m;

  b = require('../../../lib/i18n/en');

  m = require('./server_en');

  $.extend(window, {
    _i: $.extend(b, m),
    _lang: 'en'
  });

}).call(this);

//# sourceMappingURL=en.js.map
