// Generated by CoffeeScript 1.12.7
(function() {
  var PROTO_PATH, front, getCid, grpc, ip, notify, push, server;

  ip = require('ip');

  PROTO_PATH = '/Users/alex/Pictures/grpc/front/front.proto';

  grpc = require('grpc');

  front = grpc.load(PROTO_PATH).front;

  getCid = function(call, callback) {
    log('getCid');
    log(call.request);
    return callback(null, {
      ret: 1,
      cid: ip.address()
    });
  };

  push = function(call, callback) {
    log('push');
    log(call.request.uid);
    log(call.request.msg);
    return callback(null, {
      ret: 1,
      message: 'zzzzz'
    });
  };

  notify = function(call, callback) {
    log('notify');
    return log(call.request);
  };

  server = new grpc.Server();

  server.addProtoService(front.Front.service, {
    push: push,
    notify: notify,
    getCid: getCid
  });

  server.bind('0.0.0.0:12390', grpc.ServerCredentials.createInsecure());

  server.start();

  log(server);

  log('grpc server started');

}).call(this);

//# sourceMappingURL=rg_server.js.map
