// Generated by CoffeeScript 1.12.7
(function() {
  (function() {
    var pm;
    pm = function(ob) {
      return window.parent.postMessage(ob, '*');
    };
    window.__pvp = (function() {
      this.gmStart = function() {
        return pm({
          uid: this.uid,
          rid: this.rid,
          type: 'GameRoundStart'
        });
      };
      this.gmEnd = function() {
        return pm({
          uid: this.uid,
          rid: this.rid,
          type: 'GameRoundStop'
        });
      };
      this.gmProc = function(op) {
        console.log('uid');
        console.log(this.uid);
        return pm({
          type: 'GameRoundProgress',
          uid: this.uid,
          rid: this.rid,
          opt: op
        });
      };
      return this;
    })();
    return window.addEventListener('message', function(e) {
      console.log(e.source);
      console.log(window.parent);
      if (e.source !== window.parent) {
        return;
      } else if (e.data.timeout) {
        this.gmEnd();
        return;
      }
      if (!__pvp.uid) {
        __pvp.uid = e.data.uid;
        __pvp.rid = e.data.rid;
      }
      console.log('game part started...');
      console.log(__pvp.gmStart);
      return __pvp.gmStart();
    });
  })();

}).call(this);

//# sourceMappingURL=sdk.js.map
