// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    outPut: '/Users/aibo/project/gameMgr/dist/lib',
    entry: function(path, lib, bower) {
      return {
        main: [path + 'app/main']
      };
    }
  };

}).call(this);

//# sourceMappingURL=webpack.js.map
