// Generated by CoffeeScript 1.12.7
(function() {
  m.order = {};

  require('./meta/status/order');

  cf.view.ipBtn('', 'order', ctn, {
    func: function() {
      var opt;
      opt = {
        q: {
          'owner._id': user.id
        }
      };
      return $.get(util.restUrl('shop'), opt, (function(_this) {
        return function(res) {
          cf._sh = res.entities[0];
          if (cf._sh) {
            return cf.r('order/list');
          } else {
            popMsg("请先录入验配中心信息", 'warning');
            return cf.r('home/shop');
          }
        };
      })(this));
    },
    viewOpt: {
      style: 'panel-info',
      prop: [
        _ep('username'), _ep('user:gender'), m._number('age', {
          label: '年龄'
        }), _ep('phone'), {
          code: 'shop',
          type: 'text',
          showText: function(v, d) {
            if (v) {
              return "<a target='_blank' href='/shop/" + v._id + "'>" + v.title + "</a>";
            }
          }
        }, {
          code: 'consultant',
          type: 'text',
          showText: function(v, d) {
            if (v) {
              return "<a target='_blank' href='/consultant/" + v._id + "'>" + v.username + "</a>";
            }
          }
        }, {
          code: 'appointmentTime',
          type: 'text',
          label: '预约时间',
          showText: function(v) {
            return util.prettyDate(v);
          }
        }, {
          code: 'symptom',
          type: 'text'
        }, {
          code: 'memo',
          type: 'text'
        }, {
          code: 'proc',
          type: 'text'
        }
      ],
      btns: ['back']
    },
    listOpt: {
      _attrs: function() {
        return 'username,status,appointmentTime,symptom,consultant';
      },
      itemBtns: ['processOrderStatus', 'del'],
      criteriaOpt: function() {
        if (!cf._sh) {
          throw "rt::order";
        }
        return {
          q: {
            'shop._id': cf._sh._id
          }
        };
      },
      btns: [],
      modelOpt: {
        tagName: 'a'
      },
      itemContext: function(d) {
        return $.extend(d, {
          btn: true,
          subTitle: "<span class='label label-info'>" + (cf.st.text('order', d.status)) + "</span> " + (d.appointmentTime.dStr(16)),
          title: d.username + " <small>" + d.symptom + "</small>",
          attrs: {
            href: util.navUrl('order/view', d._id)
          }
        });
      }
    }
  });

}).call(this);

//# sourceMappingURL=order.js.map
