// Generated by CoffeeScript 1.12.7
(function() {
  var _ot, _otQuery, sOpt;

  require('./meta/common');

  require('./meta/brand');

  require('./meta/product');

  require('./meta/shop');

  require('./meta/consultant');

  require('./meta/school');

  _ot = {
    '>10': '10年以上',
    '5-10': '5-10年',
    '1-5': '1-5年'
  };

  _otQuery = function(key) {
    return function(v) {
      var b, d, opt, ref, res, s, year;
      opt = {};
      d = new Date();
      year = d.getFullYear();
      if (v.indexOf('-') > -1) {
        ref = v.split('-'), s = ref[0], b = ref[1];
        opt = {
          $gt: d.setFullYear(year - b) && d.pattern(),
          $lt: d.setFullYear(year - s) && d.pattern()
        };
      } else if (v.indexOf('>') > -1) {
        opt.$lt = d.setFullYear(year - v.substr(1)) && d.pattern();
      }
      res = {};
      res[key] = opt;
      return res;
    };
  };

  sOpt = {
    cols: 'col-xs-2:col-xs-10',
    toFetch: false,
    style: 'panel-default',
    toolbar: true,
    callback: function() {
      return this.$('.toolbar').html(tu.btn('重置', 'reset', 'default'));
    },
    btns: [
      {
        label: '搜索',
        cls: 'btn btn-primary btn-lg save btn-block'
      }
    ],
    noData: function() {
      return "<h3>没有搜索结果</h3>";
    },
    _save: function(t) {
      var k, opt, pp, q, ref, v;
      q = {
        status: 2
      };
      ref = this.model.attributes;
      for (k in ref) {
        v = ref[k];
        if (v) {
          if ((pp = this.prop.codeBy(k)) && pp.queryOpt) {
            opt = pp.queryOpt(v);
          } else {
            opt = {};
            opt[k] = v;
          }
          $.extend(q, opt);
        }
      }
      $('#searchPanel').removeClass('in');
      util.saveLocal("_search", q);
      cf.r("search/" + this.entity + "/" + (util.randomChar(4)));
      if (cf.mob) {
        return this.closeDlg();
      } else {
        return $('#searchPanel').hide();
      }
    }
  };

  cf.sShop = function() {
    var p;
    p = cf.mob ? 'air' : '#sShop';
    return app.dm.form(p, 'shop', $.extend({}, sOpt, {
      title: '查找助听器中心',
      prop: [
        _ep('shop:area'), m._radio('operTime', {
          attrs: {
            data: _ot
          },
          queryOpt: _otQuery('operTime')
        }), m._radio('space', {
          attrs: {
            data: {
              '>200': '200㎡以上',
              '100-200': '100-200㎡',
              '60-100': '60-100㎡',
              '<60': '60㎡以下'
            }
          },
          queryOpt: function(v) {
            var ref, space;
            space = {};
            if (v.indexOf('-') > -1) {
              ref = v.split('-'), space.$gt__i = ref[0], space.$lt__i = ref[1];
            } else if (v.indexOf('<') > -1) {
              space.$lt__i = v.substr(1);
            } else if (v.indexOf('>') > -1) {
              space.$gt__i = v.substr(1);
            }
            return {
              space: space
            };
          }
        }), m._checkbox('cust', {
          label: ' ',
          attrs: {
            data: {
              park: '可停车',
              dropIn: '可上门服务'
            }
          },
          queryOpt: function(v) {
            if (v === 'part') {
              return {
                part: '是'
              };
            } else {
              return {
                dropIn: '是'
              };
            }
          }
        }), m._radio('brand', {
          attrs: {
            entity: 'brand',
            keyVal: '_id,title',
            data: null
          },
          queryOpt: function(v) {
            if (v) {
              return {
                brand: {
                  $elemMatch: {
                    _id: v
                  }
                }
              };
            } else {
              return null;
            }
          }
        })
      ]
    }));
  };

  cf.sConsultant = function() {
    var p;
    p = cf.mob ? 'air' : '#sConsultant';
    return app.dm.form(p, 'consultant', $.extend({}, sOpt, {
      title: '查找专业验配师',
      prop: [
        _ep('area', {
          attrs: {
            prop: 'shop.postcode'
          }
        }), m._radio('exp', {
          attrs: {
            data: _ot
          },
          queryOpt: _otQuery('exp')
        }), _ep('consultant:workTitle', {
          type: 'checkbox',
          attrs: {
            inline: true
          },
          queryOpt: function(v) {
            return {
              workTitle: {
                $in: v.split(',')
              }
            };
          }
        }), _ep('consultant:strength', {
          type: 'radio',
          attrs: {
            inline: true
          },
          queryOpt: function(v) {
            return {
              strength: {
                $regex: ".*" + v + ".*"
              }
            };
          }
        }), _ep('consultant:major', {
          type: 'radio',
          attrs: {
            inline: true
          },
          queryOpt: function(v) {
            return {
              major: {
                $in: v.split(',')
              }
            };
          }
        })
      ]
    }));
  };

  cf.sProduct = function() {
    var p;
    p = cf.mob ? 'air' : '#sProduct';
    return app.dm.form(p, 'product', $.extend({}, sOpt, {
      title: '查找助听器品牌',
      prop: [
        _ep('brand:origin', {
          type: 'checkbox',
          attrs: {
            inline: true
          },
          queryOpt: function(v) {
            return {
              'brand.origin': {
                $in: v.split(',')
              }
            };
          }
        }), _ep('product:outline', {
          type: 'checkbox',
          attrs: {
            inline: true
          },
          queryOpt: function(v) {
            return {
              outline: {
                $in: v.split(',')
              }
            };
          }
        }), _ep('product:pubTime'), _ep('product:channel'), _ep('product:frequency'), _ep('product:performance', {
          checkAll: true,
          queryOpt: function(v) {
            return {
              performance: {
                $regex: ".*" + v + ".*"
              }
            };
          }
        }), _ep('product:warranty', {
          type: 'checkbox',
          attrs: {
            inline: true
          },
          queryOpt: function(v) {
            return {
              warranty: {
                $in: v.split(',')
              }
            };
          }
        }), m._radio('price', {
          attrs: {
            data: {
              '>40000': '4万以上',
              '30000-40000': '3-4万',
              '20000-30000': '2-3万',
              '10000-20000': '1-2万',
              '5000-10000': '5千-1万',
              '<5000': '5千以下'
            }
          },
          queryOpt: function(v) {
            var price, ref;
            price = {};
            if (v.indexOf('-') > -1) {
              ref = v.split('-'), price.$gt__i = ref[0], price.$lt__i = ref[1];
            } else if (v.indexOf('<') > -1) {
              price.$lt__i = v.substr(1);
            } else if (v.indexOf('>') > -1) {
              price.$gt__i = v.substr(1);
            }
            return {
              price: price
            };
          }
        })
      ]
    }));
  };

  cf.sSchool = function() {
    var p;
    p = cf.mob ? 'air' : '#sSchool';
    return app.dm.form(p, 'school', $.extend({}, sOpt, {
      title: '查找语训康复学校',
      prop: [
        _ep('area', {
          attrs: {
            prop: 'shop.postcode'
          }
        }), {
          code: 'title',
          type: 'text'
        }
      ]
    }));
  };

  if (cf.mob) {
    sOpt.fullScreen = true;
  } else {
    cf.sConsultant();
    cf.sProduct();
    cf.sShop();
    cf.sSchool();
  }

  app.enhance({
    routes: {
      '!/search/:ent/:p': 'search'
    },
    search: function(ent, p) {
      var func, pp, q, sk, title;
      title = 'title';
      func = 'head';
      pp = (function() {
        switch (ent) {
          case 'shop':
            func = 'slide';
            return 'address';
          case 'consultant':
            title = 'username';
            return 'description';
          case 'product':
            func = 'slide';
            return 'description';
          case 'school':
            return 'description';
        }
      })();
      sk = util.readLocal("_search");
      if (sk) {
        q = JSON.parse(sk);
      } else {
        cf.r('');
        return;
      }
      return this.dm.collection(this.ctn, ent, {
        className: 'col-md-12 m3 searchPanel',
        _attrs: function() {
          return "refFile," + pp + "," + title + ",brand,outline";
        },
        style: 'panel-info',
        btns: null,
        title: function() {
          return ii(ent) + '搜索结果, 您找到了 <span class="resCount text-danger">0</span> 个结果';
        },
        modelOpt: {
          tagName: 'a'
        },
        noFilter: true,
        itemContext: function(d) {
          $.extend(d, {
            title: d[title],
            attrs: {
              href: "/" + ent + "/" + d._id
            },
            brief: tu.adt(d[pp], 50),
            func: func
          });
          if (ent === 'product' && d.brand.title) {
            d.subTitle = "<br/>" + d.brand.title + " " + d.outline;
          }
          return d;
        },
        criteriaOpt: function() {
          return {
            q: q
          };
        },
        callback: function() {
          if (!cf.mob) {
            return this.$('.toolbar').append("<a class='btn btn-default' onclick='history.go(-1)'>返回</a>");
          }
        },
        afterAjax: function() {
          return $('.resCount').text(this.collection.count);
        }
      });
    }
  });

}).call(this);

//# sourceMappingURL=search.js.map
