// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = _exv('inlineObj', 'tag', {
    groupBtn: [
      {
        icon: 'edit'
      }, {
        icon: 'trash'
      }
    ],
    init: function() {
      var se;
      se = this;
      this.parent.on('click', '.trash', function(e) {
        return se.form.model.unset(se.name);
      });
      this.parent.on('click', '.edit', function(e) {
        return app.dm.form('air', se.entity, {
          data: se.val,
          btns: ['save'],
          _save: function() {
            var k, ref, res, v;
            res = {};
            ref = this.model.attributes;
            for (k in ref) {
              v = ref[k];
              if (v) {
                res[k] = v;
              }
            }
            se.form.model.set(se.name, res);
            return this.closeDlg();
          }
        });
      });
      this.target = this.parent.find('input[type=text]');
      this.target.attr('readonly', true);
      if (this.groupBtn) {
        this.target.wrap('<div class="input-group"></div>');
        return this.target.after(cf.rtp('inputBtnGroup', {
          btns: this.groupBtn
        }));
      }
    }
  });

}).call(this);

//# sourceMappingURL=inlineObj.js.map
