// Generated by CoffeeScript 1.12.7
(function() {
  meta.i18n = {
    prop: [
      _ep('key', {
        noChange: true
      }), _ep('description'), m._textarea('val')
    ],
    filter: {
      type: 'text'
    }
  };

}).call(this);

//# sourceMappingURL=i18n.js.map
