// Generated by CoffeeScript 1.12.7
(function() {
  require('../../../../lib/meta/link');

  meta.link._ = {
    tbItem: {
      title: {},
      cat: {},
      link: {},
      _btn: meta._._btn
    },
    item: ['url', 'title', 'link', 'cat', 'description']
  };

}).call(this);

//# sourceMappingURL=link.js.map
