// Generated by CoffeeScript 1.12.7
(function() {
  var m;

  m = meta;

  meta.wtUploaded = {
    prop: [
      m._text('account'), m._text('type'), m._text('mediaId'), _ep('title', {
        showText: function(v, d) {
          var it;
          return ((function() {
            var i, len, results;
            results = [];
            for (i = 0, len = d.length; i < len; i++) {
              it = d[i];
              results.push(it);
            }
            return results;
          })()).join('<br/>');
        }
      }), m._text('resId', {
        showText: function(v, d) {
          var it;
          return ((function() {
            var i, len, results;
            results = [];
            for (i = 0, len = d.length; i < len; i++) {
              it = d[i];
              results.push(it);
            }
            return results;
          })()).join('<br/>');
        }
      })
    ],
    tbBtn: ['test', 'send', 'remove', 'del'],
    btn: {
      send: function(it, e) {
        return util.iBtn("plane", 'down');
      },
      test: function(it, e) {
        return util.iBtn("user", 'down');
      },
      remove: function(it, e) {
        return util.iBtn("remove", 'down');
      }
    },
    event: {
      test: {
        type: 'click',
        fun: function(e) {
          var d;
          d = this.findData(e).attributes;
          meta.syncEntity.sAccount = {
            type: 'select',
            _name: 'account',
            data: [d.account]
          };
          return app.dm.add(null, 'syncEntity', {
            urlRoot: util.actUrl('wt/sendTest'),
            items: ['sAccount', 'testUser', "_mediaId_" + d.mediaId, "_account_" + d.account],
            mode: 'modal'
          });
        }
      },
      send: {
        type: 'click',
        fun: function(e) {
          var d;
          if (!confirm(iim('确定要发送吗？'))) {
            return;
          }
          d = this.findData(e).attributes;
          return $.post(util.actUrl('wt/sendMessNews'), {
            media_id: d.mediaId,
            account: d.account
          });
        }
      },
      remove: {
        type: 'click',
        fun: function(e) {
          var d, r;
          if (!confirm(iim('确定要删除微信远程资源吗？'))) {
            return;
          }
          d = this.findData(e).attributes;
          r = d.resId;
          r.push(d.mediaId);
          return $.post(util.actUrl('wt/removeRes'), {
            res: r.join('::'),
            account: d.account
          });
        }
      }
    }
  };

}).call(this);

//# sourceMappingURL=wtUploaded.js.map
