// Generated by CoffeeScript 1.12.7
(function() {
  cf.st.add('order', {
    waiting: {
      v: 10,
      l: '未解答'
    },
    accepted: {
      v: 20,
      l: ''
    },
    done: {
      v: 30,
      l: '已完成'
    },
    cancel: {
      v: 100,
      l: '预约取消'
    }
  });

}).call(this);

//# sourceMappingURL=answer.js.map
