// Generated by CoffeeScript 1.12.7
(function() {
  module.exports = {
    ftp: '123.57.189.54',
    url: 'yukof.postenglishtime.com',
    upload_path: '/opt/node/',
    res_path: "http://s.postenglishtime.com/",
    local_path: "http://t.yukof.com:3000/res/",
    log_path: '/opt/node/public/log/',
    db_host: '127.0.0.1',
    db_port: 37097
  };

}).call(this);

//# sourceMappingURL=setting.js.map
