// Generated by CoffeeScript 1.12.7
(function() {
  app.enhance({
    routes: {
      '!/home': 'home'
    },
    home: function() {
      var ctn, k, ob, opt, ref, v;
      this.initLayout('home', '2-10');
      ob = _.pick(user.toJSON(), 'username', 'lastLogin');
      ob.roles = user.roles;
      this.dm.view('#side', 'user', {
        cleanAll: false,
        toFetch: false,
        foot: false,
        style: 'panel-danger',
        title: '登录信息',
        data: ob,
        prop: [
          _ep('username'), {
            code: 'role',
            showText: function(v, it) {
              var i, len, str;
              str = '';
              if ((v = it.roles) && v.length) {
                for (i = 0, len = v.length; i < len; i++) {
                  it = v[i];
                  str += "<span>" + it.label + "</span>";
                }
              }
              return str;
            }
          }, {
            code: 'lastLogin',
            type: 'date'
          }
        ]
      });
      this.dm.tag('#side', {
        head: true,
        style: 'panel-success',
        title: '最新消息'
      });
      if (cf._shortcut) {
        app.dm.collection($(this._mod_ctn), 'common', {
          head: true,
          toFetch: false,
          mode: 'panel',
          title: '常用功能',
          tagClass: 'panel-body',
          data: cf._shortcut(),
          modelOpt: {
            className: 'col-xs-2',
            tmpl: 'shortcutItem'
          }
        });
      }
      $(this._mod_ctn).append('<div class="row"/>');
      ctn = $('#main .row');
      ref = cf._stat;
      for (k in ref) {
        v = ref[k];
        opt = $.extend({
          cleanAll: false,
          style: 'panel-info',
          itemBtns: ['popView', 'del'],
          btns: null,
          max: 8,
          foot: true
        }, v);
        this.dm.tb(ctn, k, opt);
      }
      return typeof cf._addStat === "function" ? cf._addStat() : void 0;
    }
  });

}).call(this);

//# sourceMappingURL=home.js.map
